import { NCERTSubject } from '@/types';

export const NCERT_SUBJECTS: NCERTSubject[] = [
  {
    id: 'math-6',
    name: 'Mathematics',
    grade: 6,
    chapters: [
      { id: 'm6-1', number: 1, title: 'Knowing Our Numbers', description: 'Introduction to large numbers and place value' },
      { id: 'm6-2', number: 2, title: 'Whole Numbers', description: 'Properties and operations on whole numbers' },
      { id: 'm6-3', number: 3, title: 'Playing with Numbers', description: 'Factors, multiples, and prime numbers' },
      { id: 'm6-4', number: 4, title: 'Basic Geometrical Ideas', description: 'Points, lines, angles, and shapes' },
      { id: 'm6-5', number: 5, title: 'Understanding Elementary Shapes', description: 'Triangles, quadrilaterals, and circles' },
      { id: 'm6-6', number: 6, title: 'Integers', description: 'Introduction to negative numbers' },
      { id: 'm6-7', number: 7, title: 'Fractions', description: 'Understanding and operations with fractions' },
      { id: 'm6-8', number: 8, title: 'Decimals', description: 'Decimal numbers and operations' },
      { id: 'm6-9', number: 9, title: 'Data Handling', description: 'Introduction to statistics' },
      { id: 'm6-10', number: 10, title: 'Mensuration', description: 'Perimeter and area' },
      { id: 'm6-11', number: 11, title: 'Algebra', description: 'Introduction to variables and expressions' },
      { id: 'm6-12', number: 12, title: 'Ratio and Proportion', description: 'Understanding ratios and proportions' },
      { id: 'm6-13', number: 13, title: 'Symmetry', description: 'Line and rotational symmetry' },
      { id: 'm6-14', number: 14, title: 'Practical Geometry', description: 'Construction of shapes' },
    ],
  },
  {
    id: 'science-6',
    name: 'Science',
    grade: 6,
    chapters: [
      { id: 's6-1', number: 1, title: 'Food: Where Does It Come From?', description: 'Sources of food' },
      { id: 's6-2', number: 2, title: 'Components of Food', description: 'Nutrients and balanced diet' },
      { id: 's6-3', number: 3, title: 'Fibre to Fabric', description: 'Natural and synthetic fibres' },
      { id: 's6-4', number: 4, title: 'Sorting Materials Into Groups', description: 'Properties of materials' },
      { id: 's6-5', number: 5, title: 'Separation of Substances', description: 'Methods of separation' },
      { id: 's6-6', number: 6, title: 'Changes Around Us', description: 'Physical and chemical changes' },
      { id: 's6-7', number: 7, title: 'Getting to Know Plants', description: 'Parts of plants' },
      { id: 's6-8', number: 8, title: 'Body Movements', description: 'Skeletal system and movement' },
      { id: 's6-9', number: 9, title: 'The Living Organisms', description: 'Characteristics of living things' },
      { id: 's6-10', number: 10, title: 'Motion and Measurement', description: 'Types of motion' },
      { id: 's6-11', number: 11, title: 'Light, Shadows and Reflections', description: 'Properties of light' },
      { id: 's6-12', number: 12, title: 'Electricity and Circuits', description: 'Simple circuits' },
      { id: 's6-13', number: 13, title: 'Fun with Magnets', description: 'Magnetic properties' },
      { id: 's6-14', number: 14, title: 'Water', description: 'Importance of water' },
      { id: 's6-15', number: 15, title: 'Air Around Us', description: 'Properties of air' },
      { id: 's6-16', number: 16, title: 'Garbage In, Garbage Out', description: 'Waste management' },
    ],
  },
  {
    id: 'sst-6',
    name: 'Social Science',
    grade: 6,
    chapters: [
      { id: 'sst6-1', number: 1, title: 'What, Where, How and When?', description: 'Understanding history' },
      { id: 'sst6-2', number: 2, title: 'On the Trail of the Earliest People', description: 'Stone Age life' },
      { id: 'sst6-3', number: 3, title: 'From Gathering to Growing Food', description: 'Agricultural revolution' },
      { id: 'sst6-4', number: 4, title: 'In the Earliest Cities', description: 'Harappan civilization' },
      { id: 'sst6-5', number: 5, title: 'What Books and Burials Tell Us', description: 'Vedic age' },
      { id: 'sst6-6', number: 6, title: 'Kingdoms, Kings and an Early Republic', description: 'Ancient kingdoms' },
      { id: 'sst6-7', number: 7, title: 'New Questions and Ideas', description: 'Religious movements' },
      { id: 'sst6-8', number: 8, title: 'Ashoka, The Emperor Who Gave Up War', description: 'Mauryan empire' },
      { id: 'sst6-9', number: 9, title: 'Understanding Diversity', description: 'India\'s diversity' },
      { id: 'sst6-10', number: 10, title: 'The Earth in the Solar System', description: 'Solar system basics' },
      { id: 'sst6-11', number: 11, title: 'Globe: Latitudes and Longitudes', description: 'Earth\'s coordinate system' },
      { id: 'sst6-12', number: 12, title: 'Motions of the Earth', description: 'Rotation and revolution' },
      { id: 'sst6-13', number: 13, title: 'Maps', description: 'Understanding maps' },
      { id: 'sst6-14', number: 14, title: 'Major Domains of the Earth', description: 'Lithosphere, atmosphere, etc.' },
    ],
  },
  {
    id: 'math-7',
    name: 'Mathematics',
    grade: 7,
    chapters: [
      { id: 'm7-1', number: 1, title: 'Integers', description: 'Operations on integers' },
      { id: 'm7-2', number: 2, title: 'Fractions and Decimals', description: 'Advanced operations' },
      { id: 'm7-3', number: 3, title: 'Data Handling', description: 'Mean, median, mode' },
      { id: 'm7-4', number: 4, title: 'Simple Equations', description: 'Linear equations' },
      { id: 'm7-5', number: 5, title: 'Lines and Angles', description: 'Types of angles and lines' },
      { id: 'm7-6', number: 6, title: 'The Triangle and Its Properties', description: 'Triangle properties' },
      { id: 'm7-7', number: 7, title: 'Congruence of Triangles', description: 'Congruence criteria' },
      { id: 'm7-8', number: 8, title: 'Comparing Quantities', description: 'Percentage and profit-loss' },
      { id: 'm7-9', number: 9, title: 'Rational Numbers', description: 'Introduction to rational numbers' },
      { id: 'm7-10', number: 10, title: 'Practical Geometry', description: 'Construction techniques' },
      { id: 'm7-11', number: 11, title: 'Perimeter and Area', description: 'Area calculations' },
      { id: 'm7-12', number: 12, title: 'Algebraic Expressions', description: 'Variables and expressions' },
      { id: 'm7-13', number: 13, title: 'Exponents and Powers', description: 'Laws of exponents' },
      { id: 'm7-14', number: 14, title: 'Symmetry', description: 'Advanced symmetry' },
      { id: 'm7-15', number: 15, title: 'Visualising Solid Shapes', description: '3D geometry' },
    ],
  },
  {
    id: 'science-7',
    name: 'Science',
    grade: 7,
    chapters: [
      { id: 's7-1', number: 1, title: 'Nutrition in Plants', description: 'Photosynthesis' },
      { id: 's7-2', number: 2, title: 'Nutrition in Animals', description: 'Digestive system' },
      { id: 's7-3', number: 3, title: 'Heat', description: 'Temperature and heat transfer' },
      { id: 's7-4', number: 4, title: 'Acids, Bases and Salts', description: 'Chemical reactions' },
      { id: 's7-5', number: 5, title: 'Physical and Chemical Changes', description: 'Types of changes' },
      { id: 's7-6', number: 6, title: 'Respiration in Organisms', description: 'Breathing and respiration' },
      { id: 's7-7', number: 7, title: 'Transportation in Animals and Plants', description: 'Circulatory system' },
      { id: 's7-8', number: 8, title: 'Reproduction in Plants', description: 'Plant reproduction' },
      { id: 's7-9', number: 9, title: 'Motion and Time', description: 'Speed and velocity' },
      { id: 's7-10', number: 10, title: 'Electric Current and Its Effects', description: 'Electromagnets' },
      { id: 's7-11', number: 11, title: 'Light', description: 'Reflection and refraction' },
      { id: 's7-12', number: 12, title: 'Forests: Our Lifeline', description: 'Ecosystem' },
      { id: 's7-13', number: 13, title: 'Wastewater Story', description: 'Water treatment' },
    ],
  },
  {
    id: 'sst-7',
    name: 'Social Science',
    grade: 7,
    chapters: [
      { id: 'sst7-1', number: 1, title: 'Tracing Changes Through a Thousand Years', description: 'Medieval history overview' },
      { id: 'sst7-2', number: 2, title: 'New Kings and Kingdoms', description: 'Medieval dynasties' },
      { id: 'sst7-3', number: 3, title: 'The Delhi Sultans', description: 'Delhi Sultanate period' },
      { id: 'sst7-4', number: 4, title: 'The Mughal Empire', description: 'Mughal rule in India' },
      { id: 'sst7-5', number: 5, title: 'Rulers and Buildings', description: 'Architecture and power' },
      { id: 'sst7-6', number: 6, title: 'Towns, Traders and Craftspersons', description: 'Medieval economy' },
      { id: 'sst7-7', number: 7, title: 'Tribes, Nomads and Settled Communities', description: 'Social structures' },
      { id: 'sst7-8', number: 8, title: 'Devotional Paths to the Divine', description: 'Bhakti movement' },
      { id: 'sst7-9', number: 9, title: 'On Equality', description: 'Democratic values' },
      { id: 'sst7-10', number: 10, title: 'Environment', description: 'Natural and human environment' },
      { id: 'sst7-11', number: 11, title: 'Inside Our Earth', description: 'Earth\'s interior' },
      { id: 'sst7-12', number: 12, title: 'Our Changing Earth', description: 'Geological processes' },
      { id: 'sst7-13', number: 13, title: 'Air', description: 'Atmosphere and winds' },
      { id: 'sst7-14', number: 14, title: 'Water', description: 'Hydrosphere' },
    ],
  },
  {
    id: 'math-8',
    name: 'Mathematics',
    grade: 8,
    chapters: [
      { id: 'm8-1', number: 1, title: 'Rational Numbers', description: 'Operations on rational numbers' },
      { id: 'm8-2', number: 2, title: 'Linear Equations in One Variable', description: 'Solving equations' },
      { id: 'm8-3', number: 3, title: 'Understanding Quadrilaterals', description: 'Properties of quadrilaterals' },
      { id: 'm8-4', number: 4, title: 'Data Handling', description: 'Graphs and probability' },
      { id: 'm8-5', number: 5, title: 'Squares and Square Roots', description: 'Perfect squares' },
      { id: 'm8-6', number: 6, title: 'Cubes and Cube Roots', description: 'Perfect cubes' },
      { id: 'm8-7', number: 7, title: 'Comparing Quantities', description: 'Compound interest' },
      { id: 'm8-8', number: 8, title: 'Algebraic Expressions', description: 'Polynomials' },
      { id: 'm8-9', number: 9, title: 'Mensuration', description: 'Surface area and volume' },
      { id: 'm8-10', number: 10, title: 'Exponents and Powers', description: 'Scientific notation' },
      { id: 'm8-11', number: 11, title: 'Direct and Inverse Proportions', description: 'Proportions' },
      { id: 'm8-12', number: 12, title: 'Factorisation', description: 'Algebraic factorisation' },
      { id: 'm8-13', number: 13, title: 'Introduction to Graphs', description: 'Plotting graphs' },
    ],
  },
  {
    id: 'science-8',
    name: 'Science',
    grade: 8,
    chapters: [
      { id: 's8-1', number: 1, title: 'Crop Production and Management', description: 'Agricultural practices' },
      { id: 's8-2', number: 2, title: 'Microorganisms', description: 'Bacteria and viruses' },
      { id: 's8-3', number: 3, title: 'Coal and Petroleum', description: 'Fossil fuels' },
      { id: 's8-4', number: 4, title: 'Combustion and Flame', description: 'Burning and fire' },
      { id: 's8-5', number: 5, title: 'Conservation of Plants and Animals', description: 'Biodiversity' },
      { id: 's8-6', number: 6, title: 'Reproduction in Animals', description: 'Sexual reproduction' },
      { id: 's8-7', number: 7, title: 'Reaching the Age of Adolescence', description: 'Puberty' },
      { id: 's8-8', number: 8, title: 'Force and Pressure', description: 'Types of forces' },
      { id: 's8-9', number: 9, title: 'Friction', description: 'Types of friction' },
      { id: 's8-10', number: 10, title: 'Sound', description: 'Properties of sound' },
      { id: 's8-11', number: 11, title: 'Chemical Effects of Electric Current', description: 'Electrolysis' },
      { id: 's8-12', number: 12, title: 'Some Natural Phenomena', description: 'Lightning and earthquakes' },
      { id: 's8-13', number: 13, title: 'Light', description: 'Laws of reflection' },
      { id: 's8-14', number: 14, title: 'Stars and the Solar System', description: 'Astronomy' },
      { id: 's8-15', number: 15, title: 'Pollution of Air and Water', description: 'Environmental pollution' },
    ],
  },
  {
    id: 'sst-8',
    name: 'Social Science',
    grade: 8,
    chapters: [
      { id: 'sst8-1', number: 1, title: 'How, When and Where', description: 'Modern history introduction' },
      { id: 'sst8-2', number: 2, title: 'From Trade to Territory', description: 'East India Company' },
      { id: 'sst8-3', number: 3, title: 'Ruling the Countryside', description: 'Colonial land policies' },
      { id: 'sst8-4', number: 4, title: 'Tribals, Dikus and the Vision of a Golden Age', description: 'Tribal societies' },
      { id: 'sst8-5', number: 5, title: 'When People Rebel', description: '1857 revolt' },
      { id: 'sst8-6', number: 6, title: 'Colonialism and the City', description: 'Urban transformation' },
      { id: 'sst8-7', number: 7, title: 'Weavers, Iron Smelters and Factory Owners', description: 'Industrial changes' },
      { id: 'sst8-8', number: 8, title: 'Civilising the Native, Educating the Nation', description: 'Colonial education' },
      { id: 'sst8-9', number: 9, title: 'The Indian Constitution', description: 'Constitutional framework' },
      { id: 'sst8-10', number: 10, title: 'Resources', description: 'Types of resources' },
      { id: 'sst8-11', number: 11, title: 'Land, Soil, Water, Natural Vegetation and Wildlife Resources', description: 'Natural resources' },
      { id: 'sst8-12', number: 12, title: 'Agriculture', description: 'Farming in India' },
      { id: 'sst8-13', number: 13, title: 'Industries', description: 'Industrial development' },
      { id: 'sst8-14', number: 14, title: 'Human Resources', description: 'Population and skills' },
    ],
  },
  {
    id: 'math-9',
    name: 'Mathematics',
    grade: 9,
    chapters: [
      { id: 'm9-1', number: 1, title: 'Number Systems', description: 'Real numbers' },
      { id: 'm9-2', number: 2, title: 'Polynomials', description: 'Polynomial operations' },
      { id: 'm9-3', number: 3, title: 'Coordinate Geometry', description: 'Cartesian plane' },
      { id: 'm9-4', number: 4, title: 'Linear Equations in Two Variables', description: 'System of equations' },
      { id: 'm9-5', number: 5, title: 'Introduction to Euclid\'s Geometry', description: 'Axioms and postulates' },
      { id: 'm9-6', number: 6, title: 'Lines and Angles', description: 'Angle theorems' },
      { id: 'm9-7', number: 7, title: 'Triangles', description: 'Triangle theorems' },
      { id: 'm9-8', number: 8, title: 'Quadrilaterals', description: 'Properties of quadrilaterals' },
      { id: 'm9-9', number: 9, title: 'Areas of Parallelograms and Triangles', description: 'Area calculations' },
      { id: 'm9-10', number: 10, title: 'Circles', description: 'Circle properties' },
      { id: 'm9-11', number: 11, title: 'Constructions', description: 'Geometric constructions' },
      { id: 'm9-12', number: 12, title: 'Heron\'s Formula', description: 'Area of triangles' },
      { id: 'm9-13', number: 13, title: 'Surface Areas and Volumes', description: '3D mensuration' },
      { id: 'm9-14', number: 14, title: 'Statistics', description: 'Data analysis' },
      { id: 'm9-15', number: 15, title: 'Probability', description: 'Introduction to probability' },
    ],
  },
  {
    id: 'science-9',
    name: 'Science',
    grade: 9,
    chapters: [
      { id: 's9-1', number: 1, title: 'Matter in Our Surroundings', description: 'States of matter' },
      { id: 's9-2', number: 2, title: 'Is Matter Around Us Pure?', description: 'Mixtures and compounds' },
      { id: 's9-3', number: 3, title: 'Atoms and Molecules', description: 'Atomic structure' },
      { id: 's9-4', number: 4, title: 'Structure of the Atom', description: 'Subatomic particles' },
      { id: 's9-5', number: 5, title: 'The Fundamental Unit of Life', description: 'Cell structure' },
      { id: 's9-6', number: 6, title: 'Tissues', description: 'Plant and animal tissues' },
      { id: 's9-7', number: 7, title: 'Diversity in Living Organisms', description: 'Classification' },
      { id: 's9-8', number: 8, title: 'Motion', description: 'Laws of motion' },
      { id: 's9-9', number: 9, title: 'Force and Laws of Motion', description: 'Newton\'s laws' },
      { id: 's9-10', number: 10, title: 'Gravitation', description: 'Universal gravitation' },
      { id: 's9-11', number: 11, title: 'Work and Energy', description: 'Energy conservation' },
      { id: 's9-12', number: 12, title: 'Sound', description: 'Wave properties' },
      { id: 's9-13', number: 13, title: 'Why Do We Fall Ill?', description: 'Disease and health' },
      { id: 's9-14', number: 14, title: 'Natural Resources', description: 'Air, water, soil' },
      { id: 's9-15', number: 15, title: 'Improvement in Food Resources', description: 'Agriculture' },
    ],
  },
  {
    id: 'sst-9',
    name: 'Social Science',
    grade: 9,
    chapters: [
      { id: 'sst9-1', number: 1, title: 'The French Revolution', description: 'Revolution of 1789' },
      { id: 'sst9-2', number: 2, title: 'Socialism in Europe and the Russian Revolution', description: 'Socialist movements' },
      { id: 'sst9-3', number: 3, title: 'Nazism and the Rise of Hitler', description: 'Nazi Germany' },
      { id: 'sst9-4', number: 4, title: 'Forest Society and Colonialism', description: 'Environmental history' },
      { id: 'sst9-5', number: 5, title: 'Pastoralists in the Modern World', description: 'Pastoral communities' },
      { id: 'sst9-6', number: 6, title: 'What is Democracy? Why Democracy?', description: 'Democratic principles' },
      { id: 'sst9-7', number: 7, title: 'Constitutional Design', description: 'Making of constitution' },
      { id: 'sst9-8', number: 8, title: 'Electoral Politics', description: 'Elections in democracy' },
      { id: 'sst9-9', number: 9, title: 'Working of Institutions', description: 'Democratic institutions' },
      { id: 'sst9-10', number: 10, title: 'Democratic Rights', description: 'Fundamental rights' },
      { id: 'sst9-11', number: 11, title: 'India - Size and Location', description: 'Geographic features' },
      { id: 'sst9-12', number: 12, title: 'Physical Features of India', description: 'Landforms' },
      { id: 'sst9-13', number: 13, title: 'Drainage', description: 'River systems' },
      { id: 'sst9-14', number: 14, title: 'Climate', description: 'Monsoon system' },
      { id: 'sst9-15', number: 15, title: 'Natural Vegetation and Wildlife', description: 'Biodiversity' },
      { id: 'sst9-16', number: 16, title: 'Population', description: 'Demographic trends' },
    ],
  },
  {
    id: 'math-10',
    name: 'Mathematics',
    grade: 10,
    chapters: [
      { id: 'm10-1', number: 1, title: 'Real Numbers', description: 'Euclid\'s division algorithm' },
      { id: 'm10-2', number: 2, title: 'Polynomials', description: 'Zeroes of polynomials' },
      { id: 'm10-3', number: 3, title: 'Pair of Linear Equations in Two Variables', description: 'Solving systems' },
      { id: 'm10-4', number: 4, title: 'Quadratic Equations', description: 'Solving quadratics' },
      { id: 'm10-5', number: 5, title: 'Arithmetic Progressions', description: 'AP formulas' },
      { id: 'm10-6', number: 6, title: 'Triangles', description: 'Similarity' },
      { id: 'm10-7', number: 7, title: 'Coordinate Geometry', description: 'Distance formula' },
      { id: 'm10-8', number: 8, title: 'Introduction to Trigonometry', description: 'Trigonometric ratios' },
      { id: 'm10-9', number: 9, title: 'Some Applications of Trigonometry', description: 'Heights and distances' },
      { id: 'm10-10', number: 10, title: 'Circles', description: 'Tangents' },
      { id: 'm10-11', number: 11, title: 'Constructions', description: 'Tangent constructions' },
      { id: 'm10-12', number: 12, title: 'Areas Related to Circles', description: 'Sector areas' },
      { id: 'm10-13', number: 13, title: 'Surface Areas and Volumes', description: 'Combinations of solids' },
      { id: 'm10-14', number: 14, title: 'Statistics', description: 'Mean, median, mode' },
      { id: 'm10-15', number: 15, title: 'Probability', description: 'Probability calculations' },
    ],
  },
  {
    id: 'science-10',
    name: 'Science',
    grade: 10,
    chapters: [
      { id: 's10-1', number: 1, title: 'Chemical Reactions and Equations', description: 'Balancing equations' },
      { id: 's10-2', number: 2, title: 'Acids, Bases and Salts', description: 'pH scale' },
      { id: 's10-3', number: 3, title: 'Metals and Non-metals', description: 'Reactivity series' },
      { id: 's10-4', number: 4, title: 'Carbon and Its Compounds', description: 'Organic chemistry' },
      { id: 's10-5', number: 5, title: 'Periodic Classification of Elements', description: 'Periodic table' },
      { id: 's10-6', number: 6, title: 'Life Processes', description: 'Nutrition, respiration' },
      { id: 's10-7', number: 7, title: 'Control and Coordination', description: 'Nervous system' },
      { id: 's10-8', number: 8, title: 'How Do Organisms Reproduce?', description: 'Reproduction' },
      { id: 's10-9', number: 9, title: 'Heredity and Evolution', description: 'Genetics' },
      { id: 's10-10', number: 10, title: 'Light: Reflection and Refraction', description: 'Lenses and mirrors' },
      { id: 's10-11', number: 11, title: 'Human Eye and Colourful World', description: 'Vision' },
      { id: 's10-12', number: 12, title: 'Electricity', description: 'Ohm\'s law' },
      { id: 's10-13', number: 13, title: 'Magnetic Effects of Electric Current', description: 'Electromagnetism' },
      { id: 's10-14', number: 14, title: 'Sources of Energy', description: 'Renewable energy' },
      { id: 's10-15', number: 15, title: 'Our Environment', description: 'Ecosystems' },
      { id: 's10-16', number: 16, title: 'Sustainable Management of Natural Resources', description: 'Conservation' },
    ],
  },
  {
    id: 'sst-10',
    name: 'Social Science',
    grade: 10,
    chapters: [
      { id: 'sst10-1', number: 1, title: 'The Rise of Nationalism in Europe', description: 'European nationalism' },
      { id: 'sst10-2', number: 2, title: 'Nationalism in India', description: 'Freedom struggle' },
      { id: 'sst10-3', number: 3, title: 'The Making of a Global World', description: 'Globalization history' },
      { id: 'sst10-4', number: 4, title: 'The Age of Industrialisation', description: 'Industrial revolution' },
      { id: 'sst10-5', number: 5, title: 'Print Culture and the Modern World', description: 'History of printing' },
      { id: 'sst10-6', number: 6, title: 'Power Sharing', description: 'Democratic power distribution' },
      { id: 'sst10-7', number: 7, title: 'Federalism', description: 'Federal system in India' },
      { id: 'sst10-8', number: 8, title: 'Gender, Religion and Caste', description: 'Social divisions' },
      { id: 'sst10-9', number: 9, title: 'Political Parties', description: 'Party system' },
      { id: 'sst10-10', number: 10, title: 'Outcomes of Democracy', description: 'Democratic achievements' },
      { id: 'sst10-11', number: 11, title: 'Resources and Development', description: 'Resource planning' },
      { id: 'sst10-12', number: 12, title: 'Forest and Wildlife Resources', description: 'Conservation' },
      { id: 'sst10-13', number: 13, title: 'Water Resources', description: 'Water management' },
      { id: 'sst10-14', number: 14, title: 'Agriculture', description: 'Indian agriculture' },
      { id: 'sst10-15', number: 15, title: 'Minerals and Energy Resources', description: 'Mineral wealth' },
      { id: 'sst10-16', number: 16, title: 'Manufacturing Industries', description: 'Industrial sectors' },
      { id: 'sst10-17', number: 17, title: 'Lifelines of National Economy', description: 'Transport and communication' },
      { id: 'sst10-18', number: 18, title: 'Development', description: 'Economic development' },
      { id: 'sst10-19', number: 19, title: 'Sectors of the Indian Economy', description: 'Economic sectors' },
      { id: 'sst10-20', number: 20, title: 'Money and Credit', description: 'Financial system' },
      { id: 'sst10-21', number: 21, title: 'Globalisation and the Indian Economy', description: 'Economic integration' },
      { id: 'sst10-22', number: 22, title: 'Consumer Rights', description: 'Consumer protection' },
    ],
  },
];

export const LANGUAGES = [
  { id: 'english', name: 'English' },
  { id: 'hindi', name: 'हिन्दी' },
  { id: 'tamil', name: 'தமிழ்' },
  { id: 'telugu', name: 'తెలుగు' },
  { id: 'bengali', name: 'বাংলা' },
  { id: 'marathi', name: 'मराठी' },
  { id: 'gujarati', name: 'ગુજરાતી' },
  { id: 'kannada', name: 'ಕನ್ನಡ' },
  { id: 'malayalam', name: 'മലയാളം' },
  { id: 'punjabi', name: 'ਪੰਜਾਬੀ' },
];
