import { ICESESubject } from '@/types';

export const ICSE_SUBJECTS: ICESESubject[] = [
  {
    id: 'physics-9',
    name: 'Physics',
    grade: 9,
    chapters: [
      { id: 'p9-1', number: 1, title: 'Measurements and Experimentation', description: 'Physical quantities, units, and measurements' },
      { id: 'p9-2', number: 2, title: 'Motion in One Dimension', description: 'Distance, displacement, speed, velocity, and acceleration' },
      { id: 'p9-3', number: 3, title: 'Laws of Motion', description: 'Newton\'s laws and their applications' },
      { id: 'p9-4', number: 4, title: 'Pressure in Fluids and Atmospheric Pressure', description: 'Pressure, buoyancy, and Archimedes\' principle' },
      { id: 'p9-5', number: 5, title: 'Upthrust in Fluids, Archimedes\' Principle', description: 'Flotation and density' },
      { id: 'p9-6', number: 6, title: 'Heat and Energy', description: 'Temperature, heat transfer, and calorimetry' },
      { id: 'p9-7', number: 7, title: 'Reflection of Light', description: 'Laws of reflection and mirrors' },
      { id: 'p9-8', number: 8, title: 'Propagation of Sound Waves', description: 'Sound characteristics and properties' },
      { id: 'p9-9', number: 9, title: 'Current Electricity', description: 'Electric current, potential difference, and Ohm\'s law' },
      { id: 'p9-10', number: 10, title: 'Magnetism', description: 'Magnetic field, properties of magnets' },
    ],
  },
  {
    id: 'physics-10',
    name: 'Physics',
    grade: 10,
    chapters: [
      { id: 'p10-1', number: 1, title: 'Force, Work, Power and Energy', description: 'Work-energy theorem and power' },
      { id: 'p10-2', number: 2, title: 'Machines', description: 'Mechanical advantage, velocity ratio, and efficiency' },
      { id: 'p10-3', number: 3, title: 'Refraction of Light at Plane Surfaces', description: 'Laws of refraction, refractive index' },
      { id: 'p10-4', number: 4, title: 'Refraction through a Lens', description: 'Lens formula and magnification' },
      { id: 'p10-5', number: 5, title: 'Spectrum', description: 'Dispersion of light and spectrum' },
      { id: 'p10-6', number: 6, title: 'Sound', description: 'Wave motion, frequency, and amplitude' },
      { id: 'p10-7', number: 7, title: 'Current Electricity', description: 'Heating effect of current, electrical power' },
      { id: 'p10-8', number: 8, title: 'Household Circuits', description: 'Electrical wiring and safety' },
      { id: 'p10-9', number: 9, title: 'Electro-magnetism', description: 'Magnetic effect of current' },
      { id: 'p10-10', number: 10, title: 'Calorimetry', description: 'Specific heat capacity and latent heat' },
      { id: 'p10-11', number: 11, title: 'Radioactivity', description: 'Nuclear physics and radioactive decay' },
    ],
  },
  {
    id: 'chemistry-9',
    name: 'Chemistry',
    grade: 9,
    chapters: [
      { id: 'c9-1', number: 1, title: 'The Language of Chemistry', description: 'Symbols, valency, and chemical formulae' },
      { id: 'c9-2', number: 2, title: 'Chemical Changes and Reactions', description: 'Types of chemical reactions' },
      { id: 'c9-3', number: 3, title: 'Water', description: 'Composition and properties of water' },
      { id: 'c9-4', number: 4, title: 'Atomic Structure and Chemical Bonding', description: 'Structure of atom and types of bonds' },
      { id: 'c9-5', number: 5, title: 'The Periodic Table', description: 'Periodic properties and classification' },
      { id: 'c9-6', number: 6, title: 'Study of Gas Laws', description: 'Boyle\'s and Charles\' laws' },
      { id: 'c9-7', number: 7, title: 'Atmospheric Pollution', description: 'Air pollution and its effects' },
    ],
  },
  {
    id: 'chemistry-10',
    name: 'Chemistry',
    grade: 10,
    chapters: [
      { id: 'c10-1', number: 1, title: 'Periodic Properties and Variations of Properties', description: 'Periodic trends in properties' },
      { id: 'c10-2', number: 2, title: 'Chemical Bonding', description: 'Ionic and covalent bonding' },
      { id: 'c10-3', number: 3, title: 'Acids, Bases and Salts', description: 'Properties and reactions' },
      { id: 'c10-4', number: 4, title: 'Analytical Chemistry', description: 'Qualitative analysis and tests' },
      { id: 'c10-5', number: 5, title: 'Mole Concept and Stoichiometry', description: 'Calculations in chemistry' },
      { id: 'c10-6', number: 6, title: 'Electrolysis', description: 'Electrochemical processes' },
      { id: 'c10-7', number: 7, title: 'Metallurgy', description: 'Extraction and purification of metals' },
      { id: 'c10-8', number: 8, title: 'Study of Compounds', description: 'Ammonia, nitric acid, and fertilizers' },
      { id: 'c10-9', number: 9, title: 'Organic Chemistry', description: 'Hydrocarbons and functional groups' },
    ],
  },
  {
    id: 'biology-9',
    name: 'Biology',
    grade: 9,
    chapters: [
      { id: 'b9-1', number: 1, title: 'Introducing Biology', description: 'Scope and importance of biology' },
      { id: 'b9-2', number: 2, title: 'Cell: The Unit of Life', description: 'Cell structure and organelles' },
      { id: 'b9-3', number: 3, title: 'Tissues', description: 'Plant and animal tissues' },
      { id: 'b9-4', number: 4, title: 'The Flower', description: 'Parts and functions of flowers' },
      { id: 'b9-5', number: 5, title: 'Pollination and Fertilization', description: 'Reproductive processes in plants' },
      { id: 'b9-6', number: 6, title: 'Seeds: Structure and Germination', description: 'Seed structure and germination' },
      { id: 'b9-7', number: 7, title: 'Respiration in Plants', description: 'Aerobic and anaerobic respiration' },
      { id: 'b9-8', number: 8, title: 'Human Digestive System', description: 'Digestion and absorption' },
      { id: 'b9-9', number: 9, title: 'Human Respiratory System', description: 'Breathing and gaseous exchange' },
      { id: 'b9-10', number: 10, title: 'Human Circulatory System', description: 'Blood circulation and heart' },
      { id: 'b9-11', number: 11, title: 'The Excretory System', description: 'Kidney structure and function' },
      { id: 'b9-12', number: 12, title: 'The Nervous System', description: 'Human nervous system and reflex action' },
      { id: 'b9-13', number: 13, title: 'The Sense Organs', description: 'Eye, ear, and other sense organs' },
      { id: 'b9-14', number: 14, title: 'Health and Hygiene', description: 'Personal and public health' },
    ],
  },
  {
    id: 'biology-10',
    name: 'Biology',
    grade: 10,
    chapters: [
      { id: 'b10-1', number: 1, title: 'Photosynthesis', description: 'Process of photosynthesis and factors' },
      { id: 'b10-2', number: 2, title: 'Chemical Coordination in Plants', description: 'Plant hormones and growth' },
      { id: 'b10-3', number: 3, title: 'Chemical Coordination in Animals', description: 'Endocrine system and hormones' },
      { id: 'b10-4', number: 4, title: 'The Reproductive System', description: 'Human reproductive organs' },
      { id: 'b10-5', number: 5, title: 'Genetics: Some Basic Fundamentals', description: 'Mendelian genetics and inheritance' },
      { id: 'b10-6', number: 6, title: 'Evolution', description: 'Theories of evolution and evidences' },
      { id: 'b10-7', number: 7, title: 'The Human Population', description: 'Population growth and control' },
      { id: 'b10-8', number: 8, title: 'Pollution', description: 'Environmental pollution and conservation' },
    ],
  },
  {
    id: 'maths-9',
    name: 'Mathematics',
    grade: 9,
    chapters: [
      { id: 'm9-1', number: 1, title: 'Rational and Irrational Numbers', description: 'Number systems and properties' },
      { id: 'm9-2', number: 2, title: 'Compound Interest', description: 'Interest calculations and applications' },
      { id: 'm9-3', number: 3, title: 'Expansions', description: 'Algebraic expansions and identities' },
      { id: 'm9-4', number: 4, title: 'Factorization', description: 'Factorizing algebraic expressions' },
      { id: 'm9-5', number: 5, title: 'Simultaneous Linear Equations', description: 'Solving systems of equations' },
      { id: 'm9-6', number: 6, title: 'Indices', description: 'Laws of indices and exponents' },
      { id: 'm9-7', number: 7, title: 'Logarithms', description: 'Logarithmic functions and properties' },
      { id: 'm9-8', number: 8, title: 'Triangles', description: 'Congruency and properties' },
      { id: 'm9-9', number: 9, title: 'Rectilinear Figures', description: 'Quadrilaterals and polygons' },
      { id: 'm9-10', number: 10, title: 'Area Theorems', description: 'Area of triangles and quadrilaterals' },
      { id: 'm9-11', number: 11, title: 'Mid-point and Intercept Theorems', description: 'Geometric theorems' },
      { id: 'm9-12', number: 12, title: 'Pythagoras Theorem', description: 'Pythagoras theorem and applications' },
      { id: 'm9-13', number: 13, title: 'Circle', description: 'Properties of circles' },
      { id: 'm9-14', number: 14, title: 'Mensuration', description: 'Area and perimeter calculations' },
      { id: 'm9-15', number: 15, title: 'Trigonometrical Ratios', description: 'Introduction to trigonometry' },
      { id: 'm9-16', number: 16, title: 'Statistics', description: 'Data handling and analysis' },
      { id: 'm9-17', number: 17, title: 'Mean and Median', description: 'Measures of central tendency' },
      { id: 'm9-18', number: 18, title: 'Coordinate Geometry', description: 'Distance and section formula' },
    ],
  },
  {
    id: 'maths-10',
    name: 'Mathematics',
    grade: 10,
    chapters: [
      { id: 'm10-1', number: 1, title: 'Goods and Service Tax', description: 'GST calculations' },
      { id: 'm10-2', number: 2, title: 'Banking', description: 'Banking operations and calculations' },
      { id: 'm10-3', number: 3, title: 'Shares and Dividends', description: 'Stock market and investments' },
      { id: 'm10-4', number: 4, title: 'Linear Inequations', description: 'Solving inequalities' },
      { id: 'm10-5', number: 5, title: 'Quadratic Equations', description: 'Solving quadratic equations' },
      { id: 'm10-6', number: 6, title: 'Ratio and Proportion', description: 'Advanced ratio problems' },
      { id: 'm10-7', number: 7, title: 'Factorization', description: 'Factorizing polynomials' },
      { id: 'm10-8', number: 8, title: 'Matrices', description: 'Matrix operations' },
      { id: 'm10-9', number: 9, title: 'Arithmetic and Geometric Progressions', description: 'Sequences and series' },
      { id: 'm10-10', number: 10, title: 'Reflection', description: 'Reflection in coordinate geometry' },
      { id: 'm10-11', number: 11, title: 'Similarity', description: 'Similar triangles and theorems' },
      { id: 'm10-12', number: 12, title: 'Loci', description: 'Locus and its applications' },
      { id: 'm10-13', number: 13, title: 'Circle', description: 'Tangents and properties of circles' },
      { id: 'm10-14', number: 14, title: 'Constructions', description: 'Geometric constructions' },
      { id: 'm10-15', number: 15, title: 'Mensuration', description: 'Surface area and volume' },
      { id: 'm10-16', number: 16, title: 'Trigonometry', description: 'Heights and distances' },
      { id: 'm10-17', number: 17, title: 'Statistics', description: 'Mean, median, mode, and ogives' },
      { id: 'm10-18', number: 18, title: 'Probability', description: 'Probability calculations' },
      { id: 'm10-19', number: 19, title: 'Coordinate Geometry', description: 'Equation of a line' },
    ],
  },
  {
    id: 'history-civics-9',
    name: 'History and Civics',
    grade: 9,
    chapters: [
      { id: 'hc9-1', number: 1, title: 'The Harappan Civilization', description: 'Early civilization and culture' },
      { id: 'hc9-2', number: 2, title: 'The Vedic Period', description: 'Vedic culture and society' },
      { id: 'hc9-3', number: 3, title: 'Jainism and Buddhism', description: 'Rise of new religions' },
      { id: 'hc9-4', number: 4, title: 'The Mauryan Empire', description: 'Chandragupta and Ashoka' },
      { id: 'hc9-5', number: 5, title: 'The Sangam Age', description: 'South Indian kingdoms' },
      { id: 'hc9-6', number: 6, title: 'The Age of the Guptas', description: 'Golden age of India' },
      { id: 'hc9-7', number: 7, title: 'The Delhi Sultanate', description: 'Muslim rule in India' },
      { id: 'hc9-8', number: 8, title: 'The Mughal Empire', description: 'Mughal emperors and administration' },
      { id: 'hc9-9', number: 9, title: 'The Composite Culture', description: 'Syncretic traditions' },
      { id: 'hc9-10', number: 10, title: 'The Renaissance', description: 'European cultural revival' },
      { id: 'hc9-11', number: 11, title: 'The Reformation', description: 'Protestant reformation' },
      { id: 'hc9-12', number: 12, title: 'The Industrial Revolution', description: 'Industrial transformation' },
      { id: 'hc9-13', number: 13, title: 'Colonialism and Imperialism', description: 'European expansion' },
      { id: 'hc9-14', number: 14, title: 'The Indian Constitution', description: 'Making of Indian constitution' },
      { id: 'hc9-15', number: 15, title: 'Fundamental Rights and Duties', description: 'Rights and responsibilities' },
      { id: 'hc9-16', number: 16, title: 'Directive Principles', description: 'State policy guidelines' },
      { id: 'hc9-17', number: 17, title: 'The Union Government', description: 'Central government structure' },
      { id: 'hc9-18', number: 18, title: 'The State Government', description: 'State administration' },
      { id: 'hc9-19', number: 19, title: 'Local Self-Government', description: 'Panchayati Raj and municipalities' },
    ],
  },
  {
    id: 'history-civics-10',
    name: 'History and Civics',
    grade: 10,
    chapters: [
      { id: 'hc10-1', number: 1, title: 'The Rise of Nationalism in Europe', description: 'European nationalism' },
      { id: 'hc10-2', number: 2, title: 'The First War of Independence 1857', description: 'Sepoy mutiny' },
      { id: 'hc10-3', number: 3, title: 'The Rise and Growth of Indian Nationalism', description: 'Early nationalist movements' },
      { id: 'hc10-4', number: 4, title: 'The Struggle for Independence', description: 'Freedom movement' },
      { id: 'hc10-5', number: 5, title: 'The First World War', description: 'Global conflict 1914-1918' },
      { id: 'hc10-6', number: 6, title: 'The Second World War', description: 'Global conflict 1939-1945' },
      { id: 'hc10-7', number: 7, title: 'The Rise of Dictatorships', description: 'Fascism and Nazism' },
      { id: 'hc10-8', number: 8, title: 'The United Nations', description: 'International organization' },
      { id: 'hc10-9', number: 9, title: 'India and the World', description: 'Foreign policy and relations' },
      { id: 'hc10-10', number: 10, title: 'The Union Legislature', description: 'Parliament and lawmaking' },
      { id: 'hc10-11', number: 11, title: 'The Union Executive', description: 'President and Council of Ministers' },
      { id: 'hc10-12', number: 12, title: 'The Union Judiciary', description: 'Supreme Court and judicial system' },
      { id: 'hc10-13', number: 13, title: 'Election Commission', description: 'Electoral system in India' },
      { id: 'hc10-14', number: 14, title: 'Political Parties', description: 'Democracy and party system' },
      { id: 'hc10-15', number: 15, title: 'Democracy and Responsible Citizenship', description: 'Citizens role in democracy' },
    ],
  },
  {
    id: 'computer-applications-9',
    name: 'Computer Applications',
    grade: 9,
    chapters: [
      { id: 'ca9-1', number: 1, title: 'Introduction to Computer Systems', description: 'Hardware, software, and types of computers' },
      { id: 'ca9-2', number: 2, title: 'Number System', description: 'Binary, decimal, octal, and hexadecimal' },
      { id: 'ca9-3', number: 3, title: 'Computer Memory', description: 'RAM, ROM, and storage devices' },
      { id: 'ca9-4', number: 4, title: 'Boolean Algebra', description: 'Logic gates and Boolean operations' },
      { id: 'ca9-5', number: 5, title: 'Problem Solving', description: 'Algorithms and flowcharts' },
      { id: 'ca9-6', number: 6, title: 'Java Fundamentals', description: 'Introduction to Java programming' },
      { id: 'ca9-7', number: 7, title: 'Tokens and Data Types', description: 'Keywords, identifiers, and data types' },
      { id: 'ca9-8', number: 8, title: 'Operators', description: 'Arithmetic, relational, and logical operators' },
      { id: 'ca9-9', number: 9, title: 'Input and Output', description: 'Scanner class and print statements' },
      { id: 'ca9-10', number: 10, title: 'Conditional Statements', description: 'if, if-else, switch statements' },
      { id: 'ca9-11', number: 11, title: 'Iterative Statements', description: 'for, while, and do-while loops' },
      { id: 'ca9-12', number: 12, title: 'Arrays', description: 'Single and multi-dimensional arrays' },
    ],
  },
  {
    id: 'computer-applications-10',
    name: 'Computer Applications',
    grade: 10,
    chapters: [
      { id: 'ca10-1', number: 1, title: 'Object Oriented Programming', description: 'OOP concepts and principles' },
      { id: 'ca10-2', number: 2, title: 'Classes and Objects', description: 'Defining classes and creating objects' },
      { id: 'ca10-3', number: 3, title: 'Constructors', description: 'Default and parameterized constructors' },
      { id: 'ca10-4', number: 4, title: 'User-defined Methods', description: 'Creating and calling methods' },
      { id: 'ca10-5', number: 5, title: 'Library Classes', description: 'String, Math, and wrapper classes' },
      { id: 'ca10-6', number: 6, title: 'Encapsulation', description: 'Data hiding and access modifiers' },
      { id: 'ca10-7', number: 7, title: 'Arrays and Strings', description: 'Array manipulation and string operations' },
      { id: 'ca10-8', number: 8, title: 'Recursion', description: 'Recursive methods and applications' },
      { id: 'ca10-9', number: 9, title: 'Inheritance', description: 'Single and multilevel inheritance' },
      { id: 'ca10-10', number: 10, title: 'Packages', description: 'Creating and using packages' },
    ],
  },
  {
    id: 'english-literature-9',
    name: 'English Literature',
    grade: 9,
    chapters: [
      { id: 'el9-1', number: 1, title: 'Julius Caesar Act 1 - William Shakespeare', description: 'Introduction to characters and conspiracy' },
      { id: 'el9-2', number: 2, title: 'Bonku Babu\'s Friend - Satyajit Ray', description: 'Short story from Treasure Chest' },
      { id: 'el9-3', number: 3, title: 'Oliver Asks for More - Charles Dickens', description: 'Classic tale of courage and justice' },
      { id: 'el9-4', number: 4, title: 'The Model Millionaire - Oscar Wilde', description: 'Short story about generosity and perception' },
      { id: 'el9-5', number: 5, title: 'The Night Mail - W H Auden', description: 'Poem celebrating the postal train journey' },
      { id: 'el9-6', number: 6, title: 'Skimbleshanks - The Railway Cat - T. S. Eliot', description: 'Whimsical poem about a railway cat' },
      { id: 'el9-7', number: 7, title: 'I Remember, I Remember - Thomas Hood', description: 'Nostalgic poem about childhood memories' },
      { id: 'el9-8', number: 8, title: 'Julius Caesar Act 2 - William Shakespeare', description: 'The conspiracy unfolds and assassination' },
      { id: 'el9-9', number: 9, title: 'The Home-coming - Rabindranath Tagore', description: 'Prose from Treasure Chest about return and belonging' },
      { id: 'el9-10', number: 10, title: 'The Boy Who Broke the Bank - Ruskin Bond', description: 'Story about rumors and consequences' },
      { id: 'el9-11', number: 11, title: 'A Doctor\'s Journal Entry for August 6, 1945 - Vikram Seth', description: 'Poem about Hiroshima bombing' },
      { id: 'el9-12', number: 12, title: 'A Work of Artifice - Marge Piercy', description: 'Poem exploring themes of constraint and freedom' },
    ],
  },
  {
    id: 'english-literature-10',
    name: 'English Literature',
    grade: 10,
    chapters: [
      { id: 'el10-1', number: 1, title: 'Julius Caesar Act III - William Shakespeare', description: 'The assassination of Caesar and Antony\'s funeral speech' },
      { id: 'el10-2', number: 2, title: 'Julius Caesar Act IV - William Shakespeare', description: 'Formation of the triumvirate and conflict among conspirators' },
      { id: 'el10-3', number: 3, title: 'Julius Caesar Act V - William Shakespeare', description: 'Battle of Philippi and the fall of Brutus and Cassius' },
      { id: 'el10-4', number: 4, title: 'With the Photographer - Stephen Leacock', description: 'Humorous story about a frustrating photography session' },
      { id: 'el10-5', number: 5, title: 'The Elevator - William Sleator', description: 'Suspenseful story about fear and the unknown' },
      { id: 'el10-6', number: 6, title: 'The Girl Who Can - Ama Ata Aidoo', description: 'Story about a young girl challenging societal expectations' },
      { id: 'el10-7', number: 7, title: 'The Pedestrian - Ray Bradbury', description: 'Dystopian story about individuality and conformity' },
      { id: 'el10-8', number: 8, title: 'The Last Lesson - Alphonse Daudet', description: 'Story about the importance of language and identity' },
      { id: 'el10-9', number: 9, title: 'Haunted Houses - H.W. Longfellow', description: 'Poem exploring memories and the presence of the past' },
      { id: 'el10-10', number: 10, title: 'The Glove and the Lions - Leigh Hunt', description: 'Poem about chivalry, courage, and true love' },
      { id: 'el10-11', number: 11, title: 'When Great Trees Fall - Maya Angelou', description: 'Poem about grief, loss, and the impact of great individuals' },
      { id: 'el10-12', number: 12, title: 'A Considerable Speck - Robert Frost', description: 'Poem reflecting on the value of small life forms' },
      { id: 'el10-13', number: 13, title: 'The Power of Music - Sukumar Ray', description: 'Whimsical poem about the magical effects of music' },
    ],
  },
  {
    id: 'english-language-9',
    name: 'English Language',
    grade: 9,
    chapters: [
      { id: 'el9-1', number: 1, title: 'Comprehension: Factual Passages', description: 'Understanding and analyzing factual texts' },
      { id: 'el9-2', number: 2, title: 'Comprehension: Narrative Passages', description: 'Analyzing stories and narratives' },
      { id: 'el9-3', number: 3, title: 'Grammar: Nouns and Pronouns', description: 'Types and usage of nouns and pronouns' },
      { id: 'el9-4', number: 4, title: 'Grammar: Verbs and Tenses', description: 'Verb forms and tense usage' },
      { id: 'el9-5', number: 5, title: 'Grammar: Adjectives and Adverbs', description: 'Modifiers and their proper usage' },
      { id: 'el9-6', number: 6, title: 'Grammar: Prepositions and Conjunctions', description: 'Connecting words and phrases' },
      { id: 'el9-7', number: 7, title: 'Sentence Structure: Simple and Compound', description: 'Building effective sentences' },
      { id: 'el9-8', number: 8, title: 'Sentence Structure: Complex Sentences', description: 'Using subordinate clauses' },
      { id: 'el9-9', number: 9, title: 'Composition: Narrative Writing', description: 'Writing stories and personal narratives' },
      { id: 'el9-10', number: 10, title: 'Composition: Descriptive Writing', description: 'Creating vivid descriptions' },
      { id: 'el9-11', number: 11, title: 'Composition: Letter Writing', description: 'Formal and informal letters' },
      { id: 'el9-12', number: 12, title: 'Composition: Email and Notice Writing', description: 'Modern communication formats' },
      { id: 'el9-13', number: 13, title: 'Vocabulary Building', description: 'Word power and usage' },
      { id: 'el9-14', number: 14, title: 'Idioms and Phrases', description: 'Common expressions and meanings' },
    ],
  },
  {
    id: 'english-language-10',
    name: 'English Language',
    grade: 10,
    chapters: [
      { id: 'el10-1', number: 1, title: 'Comprehension: Factual and Discursive', description: 'Advanced comprehension skills' },
      { id: 'el10-2', number: 2, title: 'Comprehension: Literary Passages', description: 'Analyzing literary texts' },
      { id: 'el10-3', number: 3, title: 'Grammar: Active and Passive Voice', description: 'Voice transformation' },
      { id: 'el10-4', number: 4, title: 'Grammar: Direct and Indirect Speech', description: 'Reported speech' },
      { id: 'el10-5', number: 5, title: 'Grammar: Modals and Their Usage', description: 'Using modal verbs effectively' },
      { id: 'el10-6', number: 6, title: 'Advanced Sentence Transformation', description: 'Complex sentence modifications' },
      { id: 'el10-7', number: 7, title: 'Composition: Argumentative Writing', description: 'Writing persuasive essays' },
      { id: 'el10-8', number: 8, title: 'Composition: Reflective Essays', description: 'Personal reflection and analysis' },
      { id: 'el10-9', number: 9, title: 'Composition: Article Writing', description: 'Writing for newspapers and magazines' },
      { id: 'el10-10', number: 10, title: 'Composition: Report Writing', description: 'Formal reports and documentation' },
      { id: 'el10-11', number: 11, title: 'Composition: Speech Writing', description: 'Crafting effective speeches' },
      { id: 'el10-12', number: 12, title: 'Comprehension Skills: Summary Writing', description: 'Condensing information effectively' },
      { id: 'el10-13', number: 13, title: 'Advanced Vocabulary and Usage', description: 'Sophisticated word choice' },
      { id: 'el10-14', number: 14, title: 'Editing and Proofreading', description: 'Error correction and improvement' },
    ],
  },
  {
    id: 'geography-9',
    name: 'Geography',
    grade: 9,
    chapters: [
      { id: 'g9-1', number: 1, title: 'Earth as a Planet', description: 'Shape, size, and movements of the Earth' },
      { id: 'g9-2', number: 2, title: 'Geographic Grid: Latitudes and Longitudes', description: 'Understanding coordinates and time zones' },
      { id: 'g9-3', number: 3, title: 'Rotation and Revolution', description: 'Effects of Earth\'s movements on day-night and seasons' },
      { id: 'g9-4', number: 4, title: 'Structure of the Earth', description: 'Layers of the Earth: crust, mantle, core' },
      { id: 'g9-5', number: 5, title: 'Landforms of the Earth', description: 'Mountains, plateaus, plains and their formation' },
      { id: 'g9-6', number: 6, title: 'Rocks', description: 'Types of rocks: igneous, sedimentary, metamorphic' },
      { id: 'g9-7', number: 7, title: 'Volcanoes', description: 'Types, causes, and effects of volcanic eruptions' },
      { id: 'g9-8', number: 8, title: 'Earthquakes', description: 'Causes, measurement, and effects of earthquakes' },
      { id: 'g9-9', number: 9, title: 'Weathering and Denudation', description: 'Physical, chemical, and biological weathering' },
      { id: 'g9-10', number: 10, title: 'Hydrosphere: Oceans', description: 'Distribution of oceans and their characteristics' },
      { id: 'g9-11', number: 11, title: 'Movement of Ocean Waters', description: 'Waves, tides, and ocean currents' },
      { id: 'g9-12', number: 12, title: 'Composition and Structure of the Atmosphere', description: 'Layers and composition of atmosphere' },
      { id: 'g9-13', number: 13, title: 'Insolation', description: 'Factors affecting distribution of insolation' },
      { id: 'g9-14', number: 14, title: 'Atmospheric Pressure and Winds', description: 'Pressure belts and wind systems' },
      { id: 'g9-15', number: 15, title: 'Humidity and Precipitation', description: 'Types of rainfall and humidity concepts' },
      { id: 'g9-16', number: 16, title: 'Natural Regions of the World', description: 'Climate zones and biomes' },
      { id: 'g9-17', number: 17, title: 'Map Work', description: 'Reading and interpreting maps' },
    ],
  },
  {
    id: 'geography-10',
    name: 'Geography',
    grade: 10,
    chapters: [
      { id: 'g10-1', number: 1, title: 'Map Study and Interpretation', description: 'Survey of India topographical maps, symbols, and scales' },
      { id: 'g10-2', number: 2, title: 'Topographical Maps', description: 'Four-figure and six-figure grid references, contours' },
      { id: 'g10-3', number: 3, title: 'Location, Extent and Physical Features of India', description: 'Position, neighbors, and major physical divisions' },
      { id: 'g10-4', number: 4, title: 'Climate of India', description: 'Monsoons, seasons, and factors affecting climate' },
      { id: 'g10-5', number: 5, title: 'Soil Resources of India', description: 'Types, distribution, and conservation of soils' },
      { id: 'g10-6', number: 6, title: 'Natural Vegetation of India', description: 'Types of forests and their distribution' },
      { id: 'g10-7', number: 7, title: 'Water Resources of India', description: 'Rivers, irrigation, and water management' },
      { id: 'g10-8', number: 8, title: 'Mineral and Energy Resources of India', description: 'Distribution of iron, coal, petroleum, and power' },
      { id: 'g10-9', number: 9, title: 'Agriculture in India', description: 'Major crops: rice, wheat, cotton, sugarcane, tea' },
      { id: 'g10-10', number: 10, title: 'Manufacturing Industries', description: 'Iron and steel, cotton textile, IT industries' },
      { id: 'g10-11', number: 11, title: 'Transport in India', description: 'Roadways, railways, airways, and waterways' },
      { id: 'g10-12', number: 12, title: 'Waste Management', description: 'Types of waste, disposal, and environmental impact' },
    ],
  },
];
