import { NCERTSubject } from '@/types';

export const NCERT_SUBJECTS: NCERTSubject[] = [
  {
    id: 'math-6',
    name: 'Mathematics',
    grade: 6,
    chapters: [
      { id: 'm6-1', number: 1, title: 'Knowing Our Numbers', description: 'Introduction to large numbers and place value' },
      { id: 'm6-2', number: 2, title: 'Whole Numbers', description: 'Properties and operations on whole numbers' },
      { id: 'm6-3', number: 3, title: 'Playing with Numbers', description: 'Factors, multiples, and prime numbers' },
      { id: 'm6-4', number: 4, title: 'Basic Geometrical Ideas', description: 'Points, lines, angles, and shapes' },
      { id: 'm6-5', number: 5, title: 'Understanding Elementary Shapes', description: 'Triangles, quadrilaterals, and circles' },
      { id: 'm6-6', number: 6, title: 'Integers', description: 'Introduction to negative numbers' },
      { id: 'm6-7', number: 7, title: 'Fractions', description: 'Understanding and operations with fractions' },
      { id: 'm6-8', number: 8, title: 'Decimals', description: 'Decimal numbers and operations' },
      { id: 'm6-9', number: 9, title: 'Data Handling', description: 'Introduction to statistics' },
      { id: 'm6-10', number: 10, title: 'Mensuration', description: 'Perimeter and area' },
      { id: 'm6-11', number: 11, title: 'Algebra', description: 'Introduction to variables and expressions' },
      { id: 'm6-12', number: 12, title: 'Ratio and Proportion', description: 'Understanding ratios and proportions' },
      { id: 'm6-13', number: 13, title: 'Symmetry', description: 'Line and rotational symmetry' },
      { id: 'm6-14', number: 14, title: 'Practical Geometry', description: 'Construction of shapes' },
    ],
  },
  {
    id: 'science-6',
    name: 'Science',
    grade: 6,
    chapters: [
      { id: 's6-1', number: 1, title: 'Food: Where Does It Come From?', description: 'Sources of food' },
      { id: 's6-2', number: 2, title: 'Components of Food', description: 'Nutrients and balanced diet' },
      { id: 's6-3', number: 3, title: 'Fibre to Fabric', description: 'Natural and synthetic fibres' },
      { id: 's6-4', number: 4, title: 'Sorting Materials Into Groups', description: 'Properties of materials' },
      { id: 's6-5', number: 5, title: 'Separation of Substances', description: 'Methods of separation' },
      { id: 's6-6', number: 6, title: 'Changes Around Us', description: 'Physical and chemical changes' },
      { id: 's6-7', number: 7, title: 'Getting to Know Plants', description: 'Parts of plants' },
      { id: 's6-8', number: 8, title: 'Body Movements', description: 'Skeletal system and movement' },
      { id: 's6-9', number: 9, title: 'The Living Organisms', description: 'Characteristics of living things' },
      { id: 's6-10', number: 10, title: 'Motion and Measurement', description: 'Types of motion' },
      { id: 's6-11', number: 11, title: 'Light, Shadows and Reflections', description: 'Properties of light' },
      { id: 's6-12', number: 12, title: 'Electricity and Circuits', description: 'Simple circuits' },
      { id: 's6-13', number: 13, title: 'Fun with Magnets', description: 'Magnetic properties' },
      { id: 's6-14', number: 14, title: 'Water', description: 'Importance of water' },
      { id: 's6-15', number: 15, title: 'Air Around Us', description: 'Properties of air' },
      { id: 's6-16', number: 16, title: 'Garbage In, Garbage Out', description: 'Waste management' },
    ],
  },
  {
    id: 'sst-6',
    name: 'Social Science',
    grade: 6,
    chapters: [
      { id: 'sst6-1', number: 1, title: 'What, Where, How and When?', description: 'Understanding history' },
      { id: 'sst6-2', number: 2, title: 'On the Trail of the Earliest People', description: 'Stone Age life' },
      { id: 'sst6-3', number: 3, title: 'From Gathering to Growing Food', description: 'Agricultural revolution' },
      { id: 'sst6-4', number: 4, title: 'In the Earliest Cities', description: 'Harappan civilization' },
      { id: 'sst6-5', number: 5, title: 'What Books and Burials Tell Us', description: 'Vedic age' },
      { id: 'sst6-6', number: 6, title: 'Kingdoms, Kings and an Early Republic', description: 'Ancient kingdoms' },
      { id: 'sst6-7', number: 7, title: 'New Questions and Ideas', description: 'Religious movements' },
      { id: 'sst6-8', number: 8, title: 'Ashoka, The Emperor Who Gave Up War', description: 'Mauryan empire' },
      { id: 'sst6-9', number: 9, title: 'Understanding Diversity', description: 'India\'s diversity' },
      { id: 'sst6-10', number: 10, title: 'The Earth in the Solar System', description: 'Solar system basics' },
      { id: 'sst6-11', number: 11, title: 'Globe: Latitudes and Longitudes', description: 'Earth\'s coordinate system' },
      { id: 'sst6-12', number: 12, title: 'Motions of the Earth', description: 'Rotation and revolution' },
      { id: 'sst6-13', number: 13, title: 'Maps', description: 'Understanding maps' },
      { id: 'sst6-14', number: 14, title: 'Major Domains of the Earth', description: 'Lithosphere, atmosphere, etc.' },
    ],
  },
  {
    id: 'math-7',
    name: 'Mathematics',
    grade: 7,
    chapters: [
      { id: 'm7-1', number: 1, title: 'Integers', description: 'Operations on integers' },
      { id: 'm7-2', number: 2, title: 'Fractions and Decimals', description: 'Advanced operations' },
      { id: 'm7-3', number: 3, title: 'Data Handling', description: 'Mean, median, mode' },
      { id: 'm7-4', number: 4, title: 'Simple Equations', description: 'Linear equations' },
      { id: 'm7-5', number: 5, title: 'Lines and Angles', description: 'Types of angles and lines' },
      { id: 'm7-6', number: 6, title: 'The Triangle and Its Properties', description: 'Triangle properties' },
      { id: 'm7-7', number: 7, title: 'Congruence of Triangles', description: 'Congruence criteria' },
      { id: 'm7-8', number: 8, title: 'Comparing Quantities', description: 'Percentage and profit-loss' },
      { id: 'm7-9', number: 9, title: 'Rational Numbers', description: 'Introduction to rational numbers' },
      { id: 'm7-10', number: 10, title: 'Practical Geometry', description: 'Construction techniques' },
      { id: 'm7-11', number: 11, title: 'Perimeter and Area', description: 'Area calculations' },
      { id: 'm7-12', number: 12, title: 'Algebraic Expressions', description: 'Variables and expressions' },
      { id: 'm7-13', number: 13, title: 'Exponents and Powers', description: 'Laws of exponents' },
      { id: 'm7-14', number: 14, title: 'Symmetry', description: 'Advanced symmetry' },
      { id: 'm7-15', number: 15, title: 'Visualising Solid Shapes', description: '3D geometry' },
    ],
  },
  {
    id: 'science-7',
    name: 'Science',
    grade: 7,
    chapters: [
      { id: 's7-1', number: 1, title: 'Nutrition in Plants', description: 'Photosynthesis' },
      { id: 's7-2', number: 2, title: 'Nutrition in Animals', description: 'Digestive system' },
      { id: 's7-3', number: 3, title: 'Heat', description: 'Temperature and heat transfer' },
      { id: 's7-4', number: 4, title: 'Acids, Bases and Salts', description: 'Chemical reactions' },
      { id: 's7-5', number: 5, title: 'Physical and Chemical Changes', description: 'Types of changes' },
      { id: 's7-6', number: 6, title: 'Respiration in Organisms', description: 'Breathing and respiration' },
      { id: 's7-7', number: 7, title: 'Transportation in Animals and Plants', description: 'Circulatory system' },
      { id: 's7-8', number: 8, title: 'Reproduction in Plants', description: 'Plant reproduction' },
      { id: 's7-9', number: 9, title: 'Motion and Time', description: 'Speed and velocity' },
      { id: 's7-10', number: 10, title: 'Electric Current and Its Effects', description: 'Electromagnets' },
      { id: 's7-11', number: 11, title: 'Light', description: 'Reflection and refraction' },
      { id: 's7-12', number: 12, title: 'Forests: Our Lifeline', description: 'Ecosystem' },
      { id: 's7-13', number: 13, title: 'Wastewater Story', description: 'Water treatment' },
    ],
  },
  {
    id: 'sst-7',
    name: 'Social Science',
    grade: 7,
    chapters: [
      { id: 'sst7-1', number: 1, title: 'Tracing Changes Through a Thousand Years', description: 'Medieval history overview' },
      { id: 'sst7-2', number: 2, title: 'New Kings and Kingdoms', description: 'Medieval dynasties' },
      { id: 'sst7-3', number: 3, title: 'The Delhi Sultans', description: 'Delhi Sultanate period' },
      { id: 'sst7-4', number: 4, title: 'The Mughal Empire', description: 'Mughal rule in India' },
      { id: 'sst7-5', number: 5, title: 'Rulers and Buildings', description: 'Architecture and power' },
      { id: 'sst7-6', number: 6, title: 'Towns, Traders and Craftspersons', description: 'Medieval economy' },
      { id: 'sst7-7', number: 7, title: 'Tribes, Nomads and Settled Communities', description: 'Social structures' },
      { id: 'sst7-8', number: 8, title: 'Devotional Paths to the Divine', description: 'Bhakti movement' },
      { id: 'sst7-9', number: 9, title: 'On Equality', description: 'Democratic values' },
      { id: 'sst7-10', number: 10, title: 'Environment', description: 'Natural and human environment' },
      { id: 'sst7-11', number: 11, title: 'Inside Our Earth', description: 'Earth\'s interior' },
      { id: 'sst7-12', number: 12, title: 'Our Changing Earth', description: 'Geological processes' },
      { id: 'sst7-13', number: 13, title: 'Air', description: 'Atmosphere and winds' },
      { id: 'sst7-14', number: 14, title: 'Water', description: 'Hydrosphere' },
    ],
  },
  {
    id: 'math-8',
    name: 'Mathematics',
    grade: 8,
    chapters: [
      { id: 'm8-1', number: 1, title: 'Rational Numbers', description: 'Operations on rational numbers' },
      { id: 'm8-2', number: 2, title: 'Linear Equations in One Variable', description: 'Solving equations' },
      { id: 'm8-3', number: 3, title: 'Understanding Quadrilaterals', description: 'Properties of quadrilaterals' },
      { id: 'm8-4', number: 4, title: 'Data Handling', description: 'Graphs and probability' },
      { id: 'm8-5', number: 5, title: 'Squares and Square Roots', description: 'Perfect squares' },
      { id: 'm8-6', number: 6, title: 'Cubes and Cube Roots', description: 'Perfect cubes' },
      { id: 'm8-7', number: 7, title: 'Comparing Quantities', description: 'Compound interest' },
      { id: 'm8-8', number: 8, title: 'Algebraic Expressions', description: 'Polynomials' },
      { id: 'm8-9', number: 9, title: 'Mensuration', description: 'Surface area and volume' },
      { id: 'm8-10', number: 10, title: 'Exponents and Powers', description: 'Scientific notation' },
      { id: 'm8-11', number: 11, title: 'Direct and Inverse Proportions', description: 'Proportions' },
      { id: 'm8-12', number: 12, title: 'Factorisation', description: 'Algebraic factorisation' },
      { id: 'm8-13', number: 13, title: 'Introduction to Graphs', description: 'Plotting graphs' },
    ],
  },
  {
    id: 'science-8',
    name: 'Science',
    grade: 8,
    chapters: [
      { id: 's8-1', number: 1, title: 'Crop Production and Management', description: 'Agricultural practices' },
      { id: 's8-2', number: 2, title: 'Microorganisms', description: 'Bacteria and viruses' },
      { id: 's8-3', number: 3, title: 'Coal and Petroleum', description: 'Fossil fuels' },
      { id: 's8-4', number: 4, title: 'Combustion and Flame', description: 'Burning and fire' },
      { id: 's8-5', number: 5, title: 'Conservation of Plants and Animals', description: 'Biodiversity' },
      { id: 's8-6', number: 6, title: 'Reproduction in Animals', description: 'Sexual reproduction' },
      { id: 's8-7', number: 7, title: 'Reaching the Age of Adolescence', description: 'Puberty' },
      { id: 's8-8', number: 8, title: 'Force and Pressure', description: 'Types of forces' },
      { id: 's8-9', number: 9, title: 'Friction', description: 'Types of friction' },
      { id: 's8-10', number: 10, title: 'Sound', description: 'Properties of sound' },
      { id: 's8-11', number: 11, title: 'Chemical Effects of Electric Current', description: 'Electrolysis' },
      { id: 's8-12', number: 12, title: 'Some Natural Phenomena', description: 'Lightning and earthquakes' },
      { id: 's8-13', number: 13, title: 'Light', description: 'Laws of reflection' },
      { id: 's8-14', number: 14, title: 'Stars and the Solar System', description: 'Astronomy' },
      { id: 's8-15', number: 15, title: 'Pollution of Air and Water', description: 'Environmental pollution' },
    ],
  },
  {
    id: 'sst-8',
    name: 'Social Science',
    grade: 8,
    chapters: [
      { id: 'sst8-1', number: 1, title: 'How, When and Where', description: 'Modern history introduction' },
      { id: 'sst8-2', number: 2, title: 'From Trade to Territory', description: 'East India Company' },
      { id: 'sst8-3', number: 3, title: 'Ruling the Countryside', description: 'Colonial land policies' },
      { id: 'sst8-4', number: 4, title: 'Tribals, Dikus and the Vision of a Golden Age', description: 'Tribal societies' },
      { id: 'sst8-5', number: 5, title: 'When People Rebel', description: '1857 revolt' },
      { id: 'sst8-6', number: 6, title: 'Colonialism and the City', description: 'Urban transformation' },
      { id: 'sst8-7', number: 7, title: 'Weavers, Iron Smelters and Factory Owners', description: 'Industrial changes' },
      { id: 'sst8-8', number: 8, title: 'Civilising the Native, Educating the Nation', description: 'Colonial education' },
      { id: 'sst8-9', number: 9, title: 'The Indian Constitution', description: 'Constitutional framework' },
      { id: 'sst8-10', number: 10, title: 'Resources', description: 'Types of resources' },
      { id: 'sst8-11', number: 11, title: 'Land, Soil, Water, Natural Vegetation and Wildlife Resources', description: 'Natural resources' },
      { id: 'sst8-12', number: 12, title: 'Agriculture', description: 'Farming in India' },
      { id: 'sst8-13', number: 13, title: 'Industries', description: 'Industrial development' },
      { id: 'sst8-14', number: 14, title: 'Human Resources', description: 'Population and skills' },
    ],
  },
  {
    id: 'math-9',
    name: 'Mathematics',
    grade: 9,
    chapters: [
      { id: 'm9-1', number: 1, title: 'Number Systems', description: 'Real numbers' },
      { id: 'm9-2', number: 2, title: 'Polynomials', description: 'Polynomial operations' },
      { id: 'm9-3', number: 3, title: 'Coordinate Geometry', description: 'Cartesian plane' },
      { id: 'm9-4', number: 4, title: 'Linear Equations in Two Variables', description: 'System of equations' },
      { id: 'm9-5', number: 5, title: 'Introduction to Euclid\'s Geometry', description: 'Axioms and postulates' },
      { id: 'm9-6', number: 6, title: 'Lines and Angles', description: 'Angle theorems' },
      { id: 'm9-7', number: 7, title: 'Triangles', description: 'Triangle theorems' },
      { id: 'm9-8', number: 8, title: 'Quadrilaterals', description: 'Properties of quadrilaterals' },
      { id: 'm9-9', number: 9, title: 'Areas of Parallelograms and Triangles', description: 'Area calculations' },
      { id: 'm9-10', number: 10, title: 'Circles', description: 'Circle properties' },
      { id: 'm9-11', number: 11, title: 'Constructions', description: 'Geometric constructions' },
      { id: 'm9-12', number: 12, title: 'Heron\'s Formula', description: 'Area of triangles' },
      { id: 'm9-13', number: 13, title: 'Surface Areas and Volumes', description: '3D mensuration' },
      { id: 'm9-14', number: 14, title: 'Statistics', description: 'Data analysis' },
      { id: 'm9-15', number: 15, title: 'Probability', description: 'Introduction to probability' },
    ],
  },
  {
    id: 'science-9',
    name: 'Science',
    grade: 9,
    chapters: [
      { id: 's9-1', number: 1, title: 'Matter in Our Surroundings', description: 'States of matter' },
      { id: 's9-2', number: 2, title: 'Is Matter Around Us Pure?', description: 'Mixtures and compounds' },
      { id: 's9-3', number: 3, title: 'Atoms and Molecules', description: 'Atomic structure' },
      { id: 's9-4', number: 4, title: 'Structure of the Atom', description: 'Subatomic particles' },
      { id: 's9-5', number: 5, title: 'The Fundamental Unit of Life', description: 'Cell structure' },
      { id: 's9-6', number: 6, title: 'Tissues', description: 'Plant and animal tissues' },
      { id: 's9-7', number: 7, title: 'Diversity in Living Organisms', description: 'Classification' },
      { id: 's9-8', number: 8, title: 'Motion', description: 'Laws of motion' },
      { id: 's9-9', number: 9, title: 'Force and Laws of Motion', description: 'Newton\'s laws' },
      { id: 's9-10', number: 10, title: 'Gravitation', description: 'Universal gravitation' },
      { id: 's9-11', number: 11, title: 'Work and Energy', description: 'Energy conservation' },
      { id: 's9-12', number: 12, title: 'Sound', description: 'Wave properties' },
      { id: 's9-13', number: 13, title: 'Why Do We Fall Ill?', description: 'Disease and health' },
      { id: 's9-14', number: 14, title: 'Natural Resources', description: 'Air, water, soil' },
      { id: 's9-15', number: 15, title: 'Improvement in Food Resources', description: 'Agriculture' },
    ],
  },
  {
    id: 'sst-9',
    name: 'Social Science',
    grade: 9,
    chapters: [
      { id: 'sst9-1', number: 1, title: 'The French Revolution', description: 'Revolution of 1789' },
      { id: 'sst9-2', number: 2, title: 'Socialism in Europe and the Russian Revolution', description: 'Socialist movements' },
      { id: 'sst9-3', number: 3, title: 'Nazism and the Rise of Hitler', description: 'Nazi Germany' },
      { id: 'sst9-4', number: 4, title: 'Forest Society and Colonialism', description: 'Environmental history' },
      { id: 'sst9-5', number: 5, title: 'Pastoralists in the Modern World', description: 'Pastoral communities' },
      { id: 'sst9-6', number: 6, title: 'What is Democracy? Why Democracy?', description: 'Democratic principles' },
      { id: 'sst9-7', number: 7, title: 'Constitutional Design', description: 'Making of constitution' },
      { id: 'sst9-8', number: 8, title: 'Electoral Politics', description: 'Elections in democracy' },
      { id: 'sst9-9', number: 9, title: 'Working of Institutions', description: 'Democratic institutions' },
      { id: 'sst9-10', number: 10, title: 'Democratic Rights', description: 'Fundamental rights' },
      { id: 'sst9-11', number: 11, title: 'India - Size and Location', description: 'Geographic features' },
      { id: 'sst9-12', number: 12, title: 'Physical Features of India', description: 'Landforms' },
      { id: 'sst9-13', number: 13, title: 'Drainage', description: 'River systems' },
      { id: 'sst9-14', number: 14, title: 'Climate', description: 'Monsoon system' },
      { id: 'sst9-15', number: 15, title: 'Natural Vegetation and Wildlife', description: 'Biodiversity' },
      { id: 'sst9-16', number: 16, title: 'Population', description: 'Demographic trends' },
    ],
  },
  {
    id: 'math-10',
    name: 'Mathematics',
    grade: 10,
    chapters: [
      { id: 'm10-1', number: 1, title: 'Real Numbers', description: 'Euclid\'s division algorithm' },
      { id: 'm10-2', number: 2, title: 'Polynomials', description: 'Zeroes of polynomials' },
      { id: 'm10-3', number: 3, title: 'Pair of Linear Equations in Two Variables', description: 'Solving systems' },
      { id: 'm10-4', number: 4, title: 'Quadratic Equations', description: 'Solving quadratics' },
      { id: 'm10-5', number: 5, title: 'Arithmetic Progressions', description: 'AP formulas' },
      { id: 'm10-6', number: 6, title: 'Triangles', description: 'Similarity' },
      { id: 'm10-7', number: 7, title: 'Coordinate Geometry', description: 'Distance formula' },
      { id: 'm10-8', number: 8, title: 'Introduction to Trigonometry', description: 'Trigonometric ratios' },
      { id: 'm10-9', number: 9, title: 'Some Applications of Trigonometry', description: 'Heights and distances' },
      { id: 'm10-10', number: 10, title: 'Circles', description: 'Tangents' },
      { id: 'm10-11', number: 11, title: 'Constructions', description: 'Tangent constructions' },
      { id: 'm10-12', number: 12, title: 'Areas Related to Circles', description: 'Sector areas' },
      { id: 'm10-13', number: 13, title: 'Surface Areas and Volumes', description: 'Combinations of solids' },
      { id: 'm10-14', number: 14, title: 'Statistics', description: 'Mean, median, mode' },
      { id: 'm10-15', number: 15, title: 'Probability', description: 'Probability calculations' },
    ],
  },
  {
    id: 'science-10',
    name: 'Science',
    grade: 10,
    chapters: [
      { id: 's10-1', number: 1, title: 'Chemical Reactions and Equations', description: 'Balancing equations' },
      { id: 's10-2', number: 2, title: 'Acids, Bases and Salts', description: 'pH scale' },
      { id: 's10-3', number: 3, title: 'Metals and Non-metals', description: 'Reactivity series' },
      { id: 's10-4', number: 4, title: 'Carbon and Its Compounds', description: 'Organic chemistry' },
      { id: 's10-5', number: 5, title: 'Periodic Classification of Elements', description: 'Periodic table' },
      { id: 's10-6', number: 6, title: 'Life Processes', description: 'Nutrition, respiration' },
      { id: 's10-7', number: 7, title: 'Control and Coordination', description: 'Nervous system' },
      { id: 's10-8', number: 8, title: 'How Do Organisms Reproduce?', description: 'Reproduction' },
      { id: 's10-9', number: 9, title: 'Heredity and Evolution', description: 'Genetics' },
      { id: 's10-10', number: 10, title: 'Light: Reflection and Refraction', description: 'Lenses and mirrors' },
      { id: 's10-11', number: 11, title: 'Human Eye and Colourful World', description: 'Vision' },
      { id: 's10-12', number: 12, title: 'Electricity', description: 'Ohm\'s law' },
      { id: 's10-13', number: 13, title: 'Magnetic Effects of Electric Current', description: 'Electromagnetism' },
      { id: 's10-14', number: 14, title: 'Sources of Energy', description: 'Renewable energy' },
      { id: 's10-15', number: 15, title: 'Our Environment', description: 'Ecosystems' },
      { id: 's10-16', number: 16, title: 'Sustainable Management of Natural Resources', description: 'Conservation' },
    ],
  },
  {
    id: 'sst-10',
    name: 'Social Science',
    grade: 10,
    chapters: [
      { id: 'sst10-1', number: 1, title: 'The Rise of Nationalism in Europe', description: 'European nationalism' },
      { id: 'sst10-2', number: 2, title: 'Nationalism in India', description: 'Freedom struggle' },
      { id: 'sst10-3', number: 3, title: 'The Making of a Global World', description: 'Globalization history' },
      { id: 'sst10-4', number: 4, title: 'The Age of Industrialisation', description: 'Industrial revolution' },
      { id: 'sst10-5', number: 5, title: 'Print Culture and the Modern World', description: 'History of printing' },
      { id: 'sst10-6', number: 6, title: 'Power Sharing', description: 'Democratic power distribution' },
      { id: 'sst10-7', number: 7, title: 'Federalism', description: 'Federal system in India' },
      { id: 'sst10-8', number: 8, title: 'Gender, Religion and Caste', description: 'Social divisions' },
      { id: 'sst10-9', number: 9, title: 'Political Parties', description: 'Party system' },
      { id: 'sst10-10', number: 10, title: 'Outcomes of Democracy', description: 'Democratic achievements' },
      { id: 'sst10-11', number: 11, title: 'Resources and Development', description: 'Resource planning' },
      { id: 'sst10-12', number: 12, title: 'Forest and Wildlife Resources', description: 'Conservation' },
      { id: 'sst10-13', number: 13, title: 'Water Resources', description: 'Water management' },
      { id: 'sst10-14', number: 14, title: 'Agriculture', description: 'Indian agriculture' },
      { id: 'sst10-15', number: 15, title: 'Minerals and Energy Resources', description: 'Mineral wealth' },
      { id: 'sst10-16', number: 16, title: 'Manufacturing Industries', description: 'Industrial sectors' },
      { id: 'sst10-17', number: 17, title: 'Lifelines of National Economy', description: 'Transport and communication' },
      { id: 'sst10-18', number: 18, title: 'Development', description: 'Economic development' },
      { id: 'sst10-19', number: 19, title: 'Sectors of the Indian Economy', description: 'Economic sectors' },
      { id: 'sst10-20', number: 20, title: 'Money and Credit', description: 'Financial system' },
      { id: 'sst10-21', number: 21, title: 'Globalisation and the Indian Economy', description: 'Economic integration' },
      { id: 'sst10-22', number: 22, title: 'Consumer Rights', description: 'Consumer protection' },
    ],
  },
  {
    id: 'physics-11',
    name: 'Physics',
    grade: 11,
    chapters: [
      { id: 'p11-1', number: 1, title: 'Physical World', description: 'Scope and excitement of physics' },
      { id: 'p11-2', number: 2, title: 'Units and Measurements', description: 'SI units, dimensional analysis, errors in measurement' },
      { id: 'p11-3', number: 3, title: 'Motion in a Straight Line', description: 'Position, velocity, acceleration, kinematic equations' },
      { id: 'p11-4', number: 4, title: 'Motion in a Plane', description: 'Vectors, projectile motion, uniform circular motion' },
      { id: 'p11-5', number: 5, title: 'Laws of Motion', description: 'Newton\'s laws, friction, circular motion dynamics' },
      { id: 'p11-6', number: 6, title: 'Work, Energy and Power', description: 'Work-energy theorem, conservation of energy, collisions' },
      { id: 'p11-7', number: 7, title: 'System of Particles and Rotational Motion', description: 'Centre of mass, moment of inertia, angular momentum' },
      { id: 'p11-8', number: 8, title: 'Gravitation', description: 'Kepler\'s laws, gravitational potential energy, orbital velocity' },
      { id: 'p11-9', number: 9, title: 'Mechanical Properties of Solids', description: 'Stress, strain, elastic moduli, Hooke\'s law' },
      { id: 'p11-10', number: 10, title: 'Mechanical Properties of Fluids', description: 'Pressure, Bernoulli\'s principle, viscosity, surface tension' },
      { id: 'p11-11', number: 11, title: 'Thermal Properties of Matter', description: 'Heat transfer, thermal expansion, calorimetry' },
      { id: 'p11-12', number: 12, title: 'Thermodynamics', description: 'Laws of thermodynamics, heat engines, entropy' },
      { id: 'p11-13', number: 13, title: 'Kinetic Theory', description: 'Ideal gas equation, kinetic interpretation of temperature' },
      { id: 'p11-14', number: 14, title: 'Oscillations', description: 'SHM, damped and forced oscillations, resonance' },
      { id: 'p11-15', number: 15, title: 'Waves', description: 'Transverse and longitudinal waves, superposition, Doppler effect' },
    ],
  },
  {
    id: 'chemistry-11',
    name: 'Chemistry',
    grade: 11,
    chapters: [
      { id: 'c11-1', number: 1, title: 'Some Basic Concepts of Chemistry', description: 'Mole concept, stoichiometry, atomic and molecular masses' },
      { id: 'c11-2', number: 2, title: 'Structure of Atom', description: 'Bohr model, quantum numbers, electronic configuration' },
      { id: 'c11-3', number: 3, title: 'Classification of Elements and Periodicity in Properties', description: 'Periodic table, periodic trends' },
      { id: 'c11-4', number: 4, title: 'Chemical Bonding and Molecular Structure', description: 'Ionic, covalent, metallic bonds, VSEPR theory' },
      { id: 'c11-5', number: 5, title: 'Thermodynamics', description: 'Enthalpy, entropy, Gibbs energy, Hess\'s law' },
      { id: 'c11-6', number: 6, title: 'Equilibrium', description: 'Chemical and ionic equilibrium, Le Chatelier\'s principle, pH' },
      { id: 'c11-7', number: 7, title: 'Redox Reactions', description: 'Oxidation-reduction, balancing redox equations' },
      { id: 'c11-8', number: 8, title: 'Organic Chemistry: Some Basic Principles and Techniques', description: 'IUPAC nomenclature, isomerism, reaction mechanisms' },
      { id: 'c11-9', number: 9, title: 'Hydrocarbons', description: 'Alkanes, alkenes, alkynes, aromatic hydrocarbons' },
      { id: 'c11-10', number: 10, title: 'The s-Block Elements', description: 'Alkali and alkaline earth metals' },
      { id: 'c11-11', number: 11, title: 'The p-Block Elements', description: 'Group 13 and 14 elements' },
      { id: 'c11-12', number: 12, title: 'Environmental Chemistry', description: 'Pollution, greenhouse effect, ozone depletion' },
      { id: 'c11-13', number: 13, title: 'States of Matter', description: 'Gas laws, ideal gas equation, intermolecular forces' },
      { id: 'c11-14', number: 14, title: 'Hydrogen', description: 'Properties, preparation, uses of hydrogen and its compounds' },
    ],
  },
  {
    id: 'biology-11',
    name: 'Biology',
    grade: 11,
    chapters: [
      { id: 'b11-1', number: 1, title: 'The Living World', description: 'Biodiversity, taxonomy, nomenclature' },
      { id: 'b11-2', number: 2, title: 'Biological Classification', description: 'Five kingdom classification, viruses, lichens' },
      { id: 'b11-3', number: 3, title: 'Plant Kingdom', description: 'Algae, bryophytes, pteridophytes, gymnosperms, angiosperms' },
      { id: 'b11-4', number: 4, title: 'Animal Kingdom', description: 'Classification of animals, phyla characteristics' },
      { id: 'b11-5', number: 5, title: 'Morphology of Flowering Plants', description: 'Root, stem, leaf, flower, fruit, seed' },
      { id: 'b11-6', number: 6, title: 'Anatomy of Flowering Plants', description: 'Tissue systems, anatomy of dicot and monocot' },
      { id: 'b11-7', number: 7, title: 'Structural Organisation in Animals', description: 'Animal tissues, organ systems' },
      { id: 'b11-8', number: 8, title: 'Cell: The Unit of Life', description: 'Cell structure, organelles, prokaryotic and eukaryotic cells' },
      { id: 'b11-9', number: 9, title: 'Biomolecules', description: 'Carbohydrates, proteins, lipids, nucleic acids, enzymes' },
      { id: 'b11-10', number: 10, title: 'Cell Cycle and Cell Division', description: 'Mitosis, meiosis, cell cycle regulation' },
      { id: 'b11-11', number: 11, title: 'Photosynthesis in Higher Plants', description: 'Light and dark reactions, C3 and C4 pathways' },
      { id: 'b11-12', number: 12, title: 'Respiration in Plants', description: 'Glycolysis, Krebs cycle, ETC, fermentation' },
      { id: 'b11-13', number: 13, title: 'Plant Growth and Development', description: 'Growth regulators, photoperiodism, vernalisation' },
      { id: 'b11-14', number: 14, title: 'Breathing and Exchange of Gases', description: 'Respiratory organs, mechanism, gas transport' },
      { id: 'b11-15', number: 15, title: 'Body Fluids and Circulation', description: 'Blood, heart, circulatory pathways' },
      { id: 'b11-16', number: 16, title: 'Excretory Products and Their Elimination', description: 'Kidney, urine formation, osmoregulation' },
      { id: 'b11-17', number: 17, title: 'Locomotion and Movement', description: 'Muscles, skeletal system, joints' },
      { id: 'b11-18', number: 18, title: 'Neural Control and Coordination', description: 'Nervous system, reflex action, sensory organs' },
      { id: 'b11-19', number: 19, title: 'Chemical Coordination and Integration', description: 'Endocrine glands, hormones, feedback mechanisms' },
      { id: 'b11-20', number: 20, title: 'Transport in Plants', description: 'Water and mineral absorption, transpiration, translocation' },
      { id: 'b11-21', number: 21, title: 'Mineral Nutrition', description: 'Essential elements, deficiency symptoms, nitrogen metabolism' },
      { id: 'b11-22', number: 22, title: 'Digestion and Absorption', description: 'Digestive system, enzymes, absorption of nutrients' },
    ],
  },
  {
    id: 'math-11',
    name: 'Mathematics',
    grade: 11,
    chapters: [
      { id: 'm11-1', number: 1, title: 'Sets', description: 'Types of sets, Venn diagrams, operations on sets' },
      { id: 'm11-2', number: 2, title: 'Relations and Functions', description: 'Cartesian product, relations, functions, domain and range' },
      { id: 'm11-3', number: 3, title: 'Trigonometric Functions', description: 'Trigonometric ratios, identities, graphs, equations' },
      { id: 'm11-4', number: 4, title: 'Complex Numbers and Quadratic Equations', description: 'Algebra of complex numbers, Argand plane, quadratic equations' },
      { id: 'm11-5', number: 5, title: 'Linear Inequalities', description: 'Algebraic solutions, graphical representation' },
      { id: 'm11-6', number: 6, title: 'Permutations and Combinations', description: 'Fundamental principle of counting, factorial, nPr, nCr' },
      { id: 'm11-7', number: 7, title: 'Binomial Theorem', description: 'Binomial theorem for positive integral indices, general term' },
      { id: 'm11-8', number: 8, title: 'Sequences and Series', description: 'AP, GP, HP, sum to n terms, special series' },
      { id: 'm11-9', number: 9, title: 'Straight Lines', description: 'Slope, various forms of equations, distance formula' },
      { id: 'm11-10', number: 10, title: 'Conic Sections', description: 'Circle, parabola, ellipse, hyperbola' },
      { id: 'm11-11', number: 11, title: 'Introduction to Three-Dimensional Geometry', description: 'Coordinate axes, distance formula, section formula' },
      { id: 'm11-12', number: 12, title: 'Limits and Derivatives', description: 'Intuitive idea of derivatives, limits, derivative of functions' },
      { id: 'm11-13', number: 13, title: 'Statistics', description: 'Measures of dispersion, mean deviation, variance, standard deviation' },
      { id: 'm11-14', number: 14, title: 'Probability', description: 'Random experiments, axiomatic approach, conditional probability' },
      { id: 'm11-15', number: 15, title: 'Mathematical Reasoning', description: 'Statements, logical operations, implications, validating statements' },
    ],
  },
  {
    id: 'history-11',
    name: 'History',
    grade: 11,
    chapters: [
      { id: 'h11-1', number: 1, title: 'From the Beginning of Time', description: 'Early societies, human evolution' },
      { id: 'h11-2', number: 2, title: 'Writing and City Life', description: 'Mesopotamian civilization, urbanisation' },
      { id: 'h11-3', number: 3, title: 'An Empire Across Three Continents', description: 'Roman Empire, political and social life' },
      { id: 'h11-4', number: 4, title: 'The Central Islamic Lands', description: 'Rise of Islam, Caliphate, economy and society' },
      { id: 'h11-5', number: 5, title: 'Nomadic Empires', description: 'Mongol Empire, social and political organisation' },
      { id: 'h11-6', number: 6, title: 'The Three Orders', description: 'Feudal society in medieval Europe' },
      { id: 'h11-7', number: 7, title: 'Changing Cultural Traditions', description: 'Renaissance, humanism, scientific revolution' },
      { id: 'h11-8', number: 8, title: 'Confrontation of Cultures', description: 'European voyages, encounters with Americas' },
      { id: 'h11-9', number: 9, title: 'The Industrial Revolution', description: 'Industrialisation, social changes, urbanisation' },
      { id: 'h11-10', number: 10, title: 'Displacing Indigenous Peoples', description: 'Colonisation of Americas and Australia' },
      { id: 'h11-11', number: 11, title: 'Paths to Modernisation', description: 'Japan and China modernisation, political changes' },
    ],
  },
  {
    id: 'geography-11',
    name: 'Geography',
    grade: 11,
    chapters: [
      { id: 'g11-1', number: 1, title: 'Geography as a Discipline', description: 'Nature, scope and branches of geography' },
      { id: 'g11-2', number: 2, title: 'The Origin and Evolution of the Earth', description: 'Nebular hypothesis, earth\'s interior, geological time scale' },
      { id: 'g11-3', number: 3, title: 'Interior of the Earth', description: 'Earth\'s structure, earthquakes, volcanoes' },
      { id: 'g11-4', number: 4, title: 'Distribution of Oceans and Continents', description: 'Continental drift, plate tectonics, sea-floor spreading' },
      { id: 'g11-5', number: 5, title: 'Minerals and Rocks', description: 'Rock types, rock cycle, mineral classification' },
      { id: 'g11-6', number: 6, title: 'Geomorphic Processes', description: 'Weathering, erosion, mass wasting, landforms' },
      { id: 'g11-7', number: 7, title: 'Landforms and Their Evolution', description: 'Fluvial, aeolian, glacial, coastal landforms' },
      { id: 'g11-8', number: 8, title: 'Composition and Structure of Atmosphere', description: 'Atmospheric layers, elements of weather' },
      { id: 'g11-9', number: 9, title: 'Solar Radiation, Heat Balance and Temperature', description: 'Insolation, heat budget, temperature distribution' },
      { id: 'g11-10', number: 10, title: 'Atmospheric Circulation and Weather Systems', description: 'Pressure belts, winds, cyclones, jet streams' },
      { id: 'g11-11', number: 11, title: 'Water in the Atmosphere', description: 'Evaporation, condensation, precipitation, cloud types' },
      { id: 'g11-12', number: 12, title: 'World Climate and Climate Change', description: 'Climate classification, global warming, El Nino' },
      { id: 'g11-13', number: 13, title: 'Water (Oceans)', description: 'Ocean circulation, temperature, salinity, tides' },
      { id: 'g11-14', number: 14, title: 'Movements of Ocean Water', description: 'Waves, currents, tides and their effects' },
      { id: 'g11-15', number: 15, title: 'Life on the Earth', description: 'Biosphere, ecosystems, biodiversity' },
      { id: 'g11-16', number: 16, title: 'Biodiversity and Conservation', description: 'Types of biodiversity, conservation strategies' },
    ],
  },
  {
    id: 'physics-12',
    name: 'Physics',
    grade: 12,
    chapters: [
      { id: 'p12-1', number: 1, title: 'Electric Charges and Fields', description: 'Coulomb\'s law, electric field, Gauss\'s law' },
      { id: 'p12-2', number: 2, title: 'Electrostatic Potential and Capacitance', description: 'Potential, capacitors, dielectrics' },
      { id: 'p12-3', number: 3, title: 'Current Electricity', description: 'Ohm\'s law, Kirchhoff\'s rules, Wheatstone bridge' },
      { id: 'p12-4', number: 4, title: 'Moving Charges and Magnetism', description: 'Biot-Savart law, Ampere\'s law, magnetic force' },
      { id: 'p12-5', number: 5, title: 'Magnetism and Matter', description: 'Magnetic properties, Earth\'s magnetism, para/dia/ferromagnetism' },
      { id: 'p12-6', number: 6, title: 'Electromagnetic Induction', description: 'Faraday\'s law, Lenz\'s law, eddy currents, inductance' },
      { id: 'p12-7', number: 7, title: 'Alternating Current', description: 'AC circuits, transformers, LC oscillations, resonance' },
      { id: 'p12-8', number: 8, title: 'Electromagnetic Waves', description: 'Maxwell\'s equations, EM spectrum, properties' },
      { id: 'p12-9', number: 9, title: 'Ray Optics and Optical Instruments', description: 'Reflection, refraction, lenses, microscopes, telescopes' },
      { id: 'p12-10', number: 10, title: 'Wave Optics', description: 'Interference, diffraction, polarisation, Young\'s experiment' },
      { id: 'p12-11', number: 11, title: 'Dual Nature of Radiation and Matter', description: 'Photoelectric effect, de Broglie wavelength' },
      { id: 'p12-12', number: 12, title: 'Atoms', description: 'Rutherford model, Bohr model, hydrogen spectrum' },
      { id: 'p12-13', number: 13, title: 'Nuclei', description: 'Nuclear structure, radioactivity, nuclear energy' },
      { id: 'p12-14', number: 14, title: 'Semiconductor Electronics', description: 'p-n junction, diodes, transistors, logic gates' },
    ],
  },
  {
    id: 'chemistry-12',
    name: 'Chemistry',
    grade: 12,
    chapters: [
      { id: 'c12-1', number: 1, title: 'The Solid State', description: 'Crystal lattices, unit cells, defects, electrical properties' },
      { id: 'c12-2', number: 2, title: 'Solutions', description: 'Types of solutions, colligative properties, Raoult\'s law' },
      { id: 'c12-3', number: 3, title: 'Electrochemistry', description: 'Conductance, electrolysis, Nernst equation, batteries' },
      { id: 'c12-4', number: 4, title: 'Chemical Kinetics', description: 'Rate of reaction, order, molecularity, Arrhenius equation' },
      { id: 'c12-5', number: 5, title: 'Surface Chemistry', description: 'Adsorption, catalysis, colloids, emulsions' },
      { id: 'c12-6', number: 6, title: 'General Principles and Processes of Isolation of Elements', description: 'Metallurgy, reduction, refining' },
      { id: 'c12-7', number: 7, title: 'The p-Block Elements', description: 'Group 15, 16, 17, 18 elements and compounds' },
      { id: 'c12-8', number: 8, title: 'The d- and f-Block Elements', description: 'Transition metals, lanthanoids, actinoids' },
      { id: 'c12-9', number: 9, title: 'Coordination Compounds', description: 'Werner\'s theory, IUPAC nomenclature, isomerism, bonding' },
      { id: 'c12-10', number: 10, title: 'Haloalkanes and Haloarenes', description: 'Nomenclature, reactions, SN1 and SN2 mechanisms' },
      { id: 'c12-11', number: 11, title: 'Alcohols, Phenols and Ethers', description: 'Preparation, properties, reactions' },
      { id: 'c12-12', number: 12, title: 'Aldehydes, Ketones and Carboxylic Acids', description: 'Nomenclature, preparation, reactions' },
      { id: 'c12-13', number: 13, title: 'Amines', description: 'Classification, preparation, properties, diazonium salts' },
      { id: 'c12-14', number: 14, title: 'Biomolecules', description: 'Carbohydrates, proteins, vitamins, nucleic acids' },
      { id: 'c12-15', number: 15, title: 'Polymers', description: 'Classification, polymerisation, biodegradable polymers' },
      { id: 'c12-16', number: 16, title: 'Chemistry in Everyday Life', description: 'Drugs, food additives, cleansing agents' },
    ],
  },
  {
    id: 'biology-12',
    name: 'Biology',
    grade: 12,
    chapters: [
      { id: 'b12-1', number: 1, title: 'Reproduction in Organisms', description: 'Asexual and sexual reproduction in organisms' },
      { id: 'b12-2', number: 2, title: 'Sexual Reproduction in Flowering Plants', description: 'Pollination, fertilisation, embryo development' },
      { id: 'b12-3', number: 3, title: 'Human Reproduction', description: 'Male and female reproductive systems, gametogenesis' },
      { id: 'b12-4', number: 4, title: 'Reproductive Health', description: 'Family planning, STDs, infertility, ART' },
      { id: 'b12-5', number: 5, title: 'Principles of Inheritance and Variation', description: 'Mendel\'s laws, linkage, sex determination, mutations' },
      { id: 'b12-6', number: 6, title: 'Molecular Basis of Inheritance', description: 'DNA, RNA, replication, transcription, translation, genetic code' },
      { id: 'b12-7', number: 7, title: 'Evolution', description: 'Origin of life, evidences, mechanisms of evolution' },
      { id: 'b12-8', number: 8, title: 'Human Health and Disease', description: 'Pathogens, immunity, AIDS, cancer, drugs and alcohol' },
      { id: 'b12-9', number: 9, title: 'Strategies for Enhancement in Food Production', description: 'Animal husbandry, plant breeding, tissue culture' },
      { id: 'b12-10', number: 10, title: 'Microbes in Human Welfare', description: 'Microbes in food, industry, sewage treatment, biogas' },
      { id: 'b12-11', number: 11, title: 'Biotechnology: Principles and Processes', description: 'Genetic engineering, PCR, cloning vectors, rDNA technology' },
      { id: 'b12-12', number: 12, title: 'Biotechnology and Its Applications', description: 'GMOs, gene therapy, transgenic animals, bioethics' },
      { id: 'b12-13', number: 13, title: 'Organisms and Populations', description: 'Organism-environment interactions, population ecology' },
      { id: 'b12-14', number: 14, title: 'Ecosystem', description: 'Structure, productivity, nutrient cycling, succession' },
      { id: 'b12-15', number: 15, title: 'Biodiversity and Conservation', description: 'Biodiversity patterns, loss, conservation strategies' },
      { id: 'b12-16', number: 16, title: 'Environmental Issues', description: 'Pollution, deforestation, global warming, ozone depletion' },
    ],
  },
  {
    id: 'math-12',
    name: 'Mathematics',
    grade: 12,
    chapters: [
      { id: 'm12-1', number: 1, title: 'Relations and Functions', description: 'Types of relations, types of functions, composition, inverse' },
      { id: 'm12-2', number: 2, title: 'Inverse Trigonometric Functions', description: 'Definitions, range, principal value, properties' },
      { id: 'm12-3', number: 3, title: 'Matrices', description: 'Types of matrices, operations, transpose, symmetric matrices' },
      { id: 'm12-4', number: 4, title: 'Determinants', description: 'Properties, minors, cofactors, adjoint, inverse, Cramer\'s rule' },
      { id: 'm12-5', number: 5, title: 'Continuity and Differentiability', description: 'Continuity, differentiability, chain rule, implicit differentiation' },
      { id: 'm12-6', number: 6, title: 'Application of Derivatives', description: 'Rate of change, tangents, maxima and minima, approximations' },
      { id: 'm12-7', number: 7, title: 'Integrals', description: 'Indefinite and definite integrals, methods of integration' },
      { id: 'm12-8', number: 8, title: 'Application of Integrals', description: 'Area under curves, area between curves' },
      { id: 'm12-9', number: 9, title: 'Differential Equations', description: 'Order, degree, formation, methods of solving' },
      { id: 'm12-10', number: 10, title: 'Vector Algebra', description: 'Types of vectors, scalar and vector products, triple products' },
      { id: 'm12-11', number: 11, title: 'Three Dimensional Geometry', description: 'Direction cosines, equations of line and plane, distances' },
      { id: 'm12-12', number: 12, title: 'Linear Programming', description: 'Mathematical formulation, graphical method, feasible region' },
      { id: 'm12-13', number: 13, title: 'Probability', description: 'Conditional probability, Bayes\' theorem, random variables, binomial distribution' },
    ],
  },
  {
    id: 'history-12',
    name: 'History',
    grade: 12,
    chapters: [
      { id: 'h12-1', number: 1, title: 'Bricks, Beads and Bones', description: 'Harappan civilisation, archaeological evidence' },
      { id: 'h12-2', number: 2, title: 'Kings, Farmers and Towns', description: 'Early states and economies, Mauryan Empire' },
      { id: 'h12-3', number: 3, title: 'Kinship, Caste and Class', description: 'Early societies from Mahabharata' },
      { id: 'h12-4', number: 4, title: 'Thinkers, Beliefs and Buildings', description: 'Buddhist and other religious history' },
      { id: 'h12-5', number: 5, title: 'Through the Eyes of Travellers', description: 'Accounts of Al-Biruni, Ibn Battuta, Bernier' },
      { id: 'h12-6', number: 6, title: 'Bhakti-Sufi Traditions', description: 'Religious developments, changes in belief' },
      { id: 'h12-7', number: 7, title: 'An Imperial Capital: Vijayanagara', description: 'Architecture, society, economy of Vijayanagara' },
      { id: 'h12-8', number: 8, title: 'Peasants, Zamindars and the State', description: 'Agrarian relations during Mughal period' },
      { id: 'h12-9', number: 9, title: 'Kings and Chronicles', description: 'Mughal courts and their histories' },
      { id: 'h12-10', number: 10, title: 'Colonialism and the Countryside', description: 'Colonial agrarian policies and their impact' },
      { id: 'h12-11', number: 11, title: 'Rebels and the Raj', description: '1857 revolt and its representation' },
      { id: 'h12-12', number: 12, title: 'Colonial Cities', description: 'Urbanisation and town planning in British India' },
      { id: 'h12-13', number: 13, title: 'Mahatma Gandhi and the Nationalist Movement', description: 'Freedom struggle and Gandhian politics' },
      { id: 'h12-14', number: 14, title: 'Understanding Partition', description: 'Politics, memories and experiences of partition' },
      { id: 'h12-15', number: 15, title: 'Framing the Constitution', description: 'Constituent Assembly debates and the making of the Constitution' },
    ],
  },
  {
    id: 'polscience-11',
    name: 'Political Science',
    grade: 11,
    chapters: [
      { id: 'ps11-1', number: 1, title: 'Constitution: Why and How?', description: 'Need for constitution, making of Indian Constitution' },
      { id: 'ps11-2', number: 2, title: 'Rights in the Indian Constitution', description: 'Fundamental rights, directive principles, relationship between rights' },
      { id: 'ps11-3', number: 3, title: 'Election and Representation', description: 'Electoral system, reservation, free and fair elections' },
      { id: 'ps11-4', number: 4, title: 'Executive', description: 'Parliamentary system, President, Prime Minister, Council of Ministers' },
      { id: 'ps11-5', number: 5, title: 'Legislature', description: 'Parliament, Rajya Sabha, Lok Sabha, law-making process' },
      { id: 'ps11-6', number: 6, title: 'Judiciary', description: 'Supreme Court, High Courts, judicial review, PIL' },
      { id: 'ps11-7', number: 7, title: 'Federalism', description: 'Federal provisions, centre-state relations, disputes' },
      { id: 'ps11-8', number: 8, title: 'Local Governments', description: 'Panchayati Raj, municipalities, 73rd and 74th amendments' },
      { id: 'ps11-9', number: 9, title: 'Constitution as a Living Document', description: 'Amendment process, basic structure doctrine, judicial interpretation' },
      { id: 'ps11-10', number: 10, title: 'The Philosophy of the Constitution', description: 'Political philosophy, procedural and substantive democracy' },
      { id: 'ps11-11', number: 11, title: 'Political Theory: An Introduction', description: 'What is politics, political theory and practice' },
      { id: 'ps11-12', number: 12, title: 'Freedom', description: 'Meaning of freedom, why do we need constraints, harm principle' },
      { id: 'ps11-13', number: 13, title: 'Equality', description: 'Significance of equality, dimensions, affirmative action' },
      { id: 'ps11-14', number: 14, title: 'Social Justice', description: 'Just distribution, Rawls theory, pursuit of social justice' },
      { id: 'ps11-15', number: 15, title: 'Rights', description: 'Rights and their origin, kinds of rights, rights and responsibilities' },
      { id: 'ps11-16', number: 16, title: 'Citizenship', description: 'Meaning, global citizenship, rights of citizens' },
      { id: 'ps11-17', number: 17, title: 'Nationalism', description: 'Nations and nationalism, national self-determination, pluralism' },
      { id: 'ps11-18', number: 18, title: 'Secularism', description: 'What is secularism, Indian model, western model' },
      { id: 'ps11-19', number: 19, title: 'Peace', description: 'Peace and violence, structural violence, peace and the state' },
      { id: 'ps11-20', number: 20, title: 'Development', description: 'What is development, different models, sustainability' },
    ],
  },
  {
    id: 'polscience-12',
    name: 'Political Science',
    grade: 12,
    chapters: [
      { id: 'ps12-1', number: 1, title: 'The Cold War Era', description: 'Emergence of two power blocs, arenas of cold war, NAM' },
      { id: 'ps12-2', number: 2, title: 'The End of Bipolarity', description: 'Disintegration of USSR, new world order, shock therapy' },
      { id: 'ps12-3', number: 3, title: 'US Hegemony in World Politics', description: 'Beginning of new world order, constraints on US hegemony' },
      { id: 'ps12-4', number: 4, title: 'Alternative Centres of Power', description: 'European Union, ASEAN, China, India as emerging power' },
      { id: 'ps12-5', number: 5, title: 'Contemporary South Asia', description: 'Democracies and military rule, India-Pakistan, India-neighbours' },
      { id: 'ps12-6', number: 6, title: 'International Organisations', description: 'UN reform, India and UN, WTO, IMF, World Bank' },
      { id: 'ps12-7', number: 7, title: 'Security in the Contemporary World', description: 'Traditional and non-traditional security, terrorism, global poverty' },
      { id: 'ps12-8', number: 8, title: 'Environment and Natural Resources', description: 'Global commons, common property, environmental movements' },
      { id: 'ps12-9', number: 9, title: 'Globalisation', description: 'Causes of globalisation, cultural consequences, India and globalisation' },
      { id: 'ps12-10', number: 10, title: 'Challenges of Nation Building', description: 'Partition, integration of states, reorganisation of states' },
      { id: 'ps12-11', number: 11, title: 'Era of One-Party Dominance', description: 'Congress dominance, socialist and communist parties, first three elections' },
      { id: 'ps12-12', number: 12, title: 'Politics of Planned Development', description: 'Five year plans, planning commission, mixed economy' },
      { id: 'ps12-13', number: 13, title: 'India\'s External Relations', description: 'Nehruvian foreign policy, Sino-Indian war, Indo-Pak wars' },
      { id: 'ps12-14', number: 14, title: 'Challenges to and Restoration of the Congress System', description: 'Congress decline, 1967 elections, split in Congress' },
      { id: 'ps12-15', number: 15, title: 'Crisis of Democratic Order', description: 'Emergency, background, lessons of Emergency' },
      { id: 'ps12-16', number: 16, title: 'Rise of Popular Movements', description: 'Chipko, Narmada Bachao, Dalit Panthers, farmers movements' },
      { id: 'ps12-17', number: 17, title: 'Regional Aspirations', description: 'Jammu and Kashmir, Punjab, Northeast, Assam' },
      { id: 'ps12-18', number: 18, title: 'Recent Developments in Indian Politics', description: 'Era of coalitions, BJP rise, communalism, caste politics' },
    ],
  },
  {
    id: 'geography-12',
    name: 'Geography',
    grade: 12,
    chapters: [
      { id: 'g12-1', number: 1, title: 'Human Geography: Nature and Scope', description: 'Nature, scope and approaches of human geography' },
      { id: 'g12-2', number: 2, title: 'The World Population: Distribution, Density and Growth', description: 'Population patterns, growth, demographic transition' },
      { id: 'g12-3', number: 3, title: 'Population Composition', description: 'Age, sex, literacy, occupational structure' },
      { id: 'g12-4', number: 4, title: 'Human Development', description: 'Concept, indicators, HDI, international comparisons' },
      { id: 'g12-5', number: 5, title: 'Primary Activities', description: 'Gathering, pastoral, mining, subsistence farming' },
      { id: 'g12-6', number: 6, title: 'Secondary Activities', description: 'Manufacturing, industries, types and factors' },
      { id: 'g12-7', number: 7, title: 'Tertiary and Quaternary Activities', description: 'Services, trade, transport, communication' },
      { id: 'g12-8', number: 8, title: 'Transport and Communication', description: 'Land, water, air transport, pipelines, communication networks' },
      { id: 'g12-9', number: 9, title: 'International Trade', description: 'Basis, types, WTO, regional trading blocs' },
      { id: 'g12-10', number: 10, title: 'Human Settlements', description: 'Rural and urban settlements, urbanisation' },
      { id: 'g12-11', number: 11, title: 'Population: Distribution, Density, Growth and Composition (India)', description: 'India\'s population dynamics' },
      { id: 'g12-12', number: 12, title: 'Migration: Types, Causes and Consequences (India)', description: 'Migration patterns in India' },
      { id: 'g12-13', number: 13, title: 'Human Development (India)', description: 'HDI in Indian context, regional disparities' },
      { id: 'g12-14', number: 14, title: 'Land Resources and Agriculture (India)', description: 'Land use, agricultural types, food security' },
      { id: 'g12-15', number: 15, title: 'Water Resources (India)', description: 'Water availability, irrigation, water conservation' },
      { id: 'g12-16', number: 16, title: 'Mineral and Energy Resources (India)', description: 'Mineral distribution, conventional and non-conventional energy' },
      { id: 'g12-17', number: 17, title: 'Manufacturing Industries (India)', description: 'Industrial location, major industries, industrial policy' },
      { id: 'g12-18', number: 18, title: 'Planning and Sustainable Development in Indian Context', description: 'Regional planning, sustainable development' },
      { id: 'g12-19', number: 19, title: 'Transport and Communication (India)', description: 'Indian transport networks, communication revolution' },
      { id: 'g12-20', number: 20, title: 'Geographical Perspective on Selected Issues and Problems', description: 'Environmental pollution, urban waste, global warming' },
    ],
  },
];

export const LANGUAGES = [
  { id: 'english', name: 'English' },
  { id: 'hindi', name: 'हिन्दी' },
  { id: 'tamil', name: 'தமிழ்' },
  { id: 'telugu', name: 'తెలుగు' },
  { id: 'bengali', name: 'বাংলা' },
  { id: 'marathi', name: 'मराठी' },
  { id: 'gujarati', name: 'ગુજરાતી' },
  { id: 'kannada', name: 'ಕನ್ನಡ' },
  { id: 'malayalam', name: 'മലയാളം' },
  { id: 'punjabi', name: 'ਪੰਜਾਬੀ' },
];
